### ISSUE TITLE
Compiler crashes if an unused private field exists

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#1001]
## Description
The compiler crashes if an unused private field exists.

## Environment

- Compiler version: branch `develop` (commit `b18ea015`)
- Operating system: Manjaro

## Steps to Reproduce
```zokrates
def main(private field x):
	return
```

```
$ zz compile -i bug.zok
Compiling bug.zok

Unconstrained variables are not allowed (found 1 occurrence) (/home/christoph/.applications/ZoKrates/zokrates_core/src/static_analysis/unconstrained_vars.rs:29:9)
This is unexpected, please submit a full bug report at https://github.com/Zokrates/ZoKrates/issues
```

**Comment by m1cm1c** [comment]
I just upgraded to commit `60f91894` and discovered that this is being caught now:

```
$ zz compile -i bug.zok 
Compiling bug.zok

Compilation failed:

bug.zok:
        Found unconstrained variables during IR analysis (found 1 occurrence)
```

This definitely is an improvement. However, wouldn't it be better to just ignore such fields to allow for easier development?

**Comment by dark64** [comment]
There is a flag `--allow-unconstrained-variables` on the `compile` command which will insert dummy constraints for unused private inputs.

**Comment by m1cm1c** [comment]
> There is a flag `--allow-unconstrained-variables` on the `compile` command which will insert dummy constraints for unused private inputs.

Cool, thanks for the info! That's really useful both for debugging and for reducing code to minimal examples of bugs. I'd be nice if this was added to the error message to inform new users that they don't have to spend a lot of time commenting out unused private inputs and modifying witnesses while trying to tackle unexpected behavior. Maybe something like:

> Compiling bug.zok
> 
> Compilation failed:
> 
> bug.zok:
>         Found unconstrained variables during IR analysis (found 1 occurrence). If this is intentional, use the --allow-unconstrained-variables switch.
