### ISSUE TITLE
Modulo does not work with type field

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#1006]
## Description

The modulo operation does not work on variables of type `field`. I'm not sure whether this should be a feature request or a bug report. On the one hand, it's a missing feature that would be really nice to have. But on the other hand, [the documentation of the operations](https://zokrates.github.io/language/operators.html) does not mention any restrictions on the `%` operator. Furthermore, it is documented to be in the same category as multiplication and division, which both work with all types. In addition to this, [the documentation of the data types](https://zokrates.github.io/language/types.html) says about the data type `field`: "Standard arithmetic operations are supported"`

## Environment

- Compiler version: branch develop (commit `af7040`)
- Operating system: Manjaro

## Steps to Reproduce

```zokrates
def main():
	field a = 7
	field b = a % 5
	return
```

```
$ zokrates compile -i bug.zok 
Compiling bug.zok

Compilation failed:

bug.zok:3:12
        Cannot apply `%` to field, field
```

**Comment by CarlJons0** [comment]
I ran into the same problem, and division also doesn't work for field types, such as 1/2, where the expected value is 0, but the result is not . Have you found a solution to the problem?

**Comment by WangXiaopai595** [comment]
I ran into the same problem, and division also doesn't work for field types, such as 1/2, where the expected value is 0, but the result is not . Have you found a solution to the problem?

**Comment by m1cm1c** [comment]
@Wangpaipai I have not found a solution. However, the behavior of division is at least documented:

> Note that for field elements, the division operation multiplies the numerator with the denominator's inverse field element. The results coincide with integer divisions for cases with remainder 0, but differ otherwise.

(https://zokrates.github.io/language/types.html)
