### ISSUE TITLE
Verifier exportation does not work for PGHR13

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#1007]
## Description

Verifier exportation does not work for PGHR13.

## Environment

- Compiler version: branch `develop` (commit `af704063`)
- Operating system: Manjaro

## Steps to Reproduce
1. Compile Zokrates with support for the libsnark backend:
```
cargo +nightly -Z package-features build --release --package zokrates_cli --features="libsnark"
```
2. Compile any Zokrates program:
```
zokrates compile -i main.zok
```
3. Create the setup with PGHR13 specified:
```
zokrates setup --backend libsnark --proving-scheme pghr13
```
4. Try to export the verifier:
```
zokrates export-verifier
Exporting verifier...
Could not deserialize verification key: missing field `alpha` at line 66 column 1
```

**Comment by dark64** [comment]
You need to specify the scheme:

```sh
$ zokrates export-verifier --proving-scheme pghr13

Exporting verifier...
Verifier exported to 'verifier.sol'
```

**Comment by m1cm1c** [comment]
Oh, thank you @dark64. I somehow thought you only needed to specify the proving scheme once (which would be for the setup).
