### ISSUE TITLE
Creating moderately sized 2D arrays

### ISSUE THREAD

**Issue by sshravan** [Zokrates/ZoKrates#1048]
## Description
I am unable to load moderately sized const 2D array. In the following code snippet, I am simply trying to load a matrix and multiply it with a scalar. However, after running for 10+ hours, the compiler simply fails.

## Environment

- Compiler version: 0.7.7 (fc55d881)
- Operating system: Ubuntu

## Steps to Reproduce
Here is the link to the [full code](https://github.com/sshravan/zok-issues/tree/main/issue-01/bug).
bug/utils/matrix.zok

```zokrates
const u32 SIZE = 1024
const field[1024][1024] MATRIX = [
	[
	       1,       2,       3,       4, ...
	],
	...
	[
	       4,       3,       2,       1, ...
	]
]

```

bug/main.zok

```zokrates
from "./utils/matrix" import MATRIX
const u32 SIZE = 1024

def main(field scalar):
    field[SIZE][SIZE] result = [[0; SIZE]; SIZE]
    for u32 i in 0..SIZE do
        for u32 j in 0..SIZE do
            result[i][j] = MATRIX[i][j] * scalar
        endfor
    endfor

    assert(result == [[0; SIZE]; SIZE])
    return
```

```bash
$ zokrates compile -i bug/main.zok
Compiling bug/main.zok

[2]    366099 killed     zokrates compile -i bug/main.zok
zokrates compile -i bug/main.zok  37104.11s user 32.63s system 99% cpu 10:21:45.32 total
```

Any suggestions to get around this is highly appreciated!

**Comment by Schaeff** [comment]
Hey @sshravan apologies for the delay on this, I'm looking into it now. The matrix file is 9MB in size, which I would respectfully disagree is "moderately sized". There are certainly things that can be improved but such sizes for a source file are going to be challenging in the foreseeable future.

Did you find a way around having such a big array?
