### ISSUE TITLE
Accept proving inputs as JSON

### ISSUE THREAD

**Issue by HarryR** [Zokrates/ZoKrates#105]
It would be good to accept proving inputs as a JSON file as I noticed people had problems working out and passing the right command-line arguments.

Using JSON for the raw inputs would avoid having to figure out the packing logic in the code that calls the prover, and would allow types from ZoKrates code to be automagically handled as the code changes.

e.g

```python
def main(public value : int16, public flag : bool, private preimage : bytes32):
   ...
```

The inputs would be:

```json
{
 "public" : {
    "value": 1234,
    "flag": true
 },
 "secret": {
    "preimage": "0x....."
 }
```

If you were going to support struct types, it would be something like:

```python
struct Derp:
    value : int16
    flag : bool

def main(public derps : Derp[2]):
   ...
```

With JSON input:

```json
{
 "public" : {
    "derps": [
       { 
           "value": 1234,
           "flag": true
       },
       { 
           "value": 1234,
           "flag": true
       }
    ]
 }
```

Note that I've made up typed variables for ZoKrates, because passing each individual bit at a time is a massive PITA. Likewise, with fixed-sized arrays of structs... it'd be really good to support these kinds of things as it'd mean that you don't have to do bits to int unpacking by hand, or handling the encoding logic yourself.

This would make EaseOfUse++

**Comment by Schaeff** [comment]
Totally agree! This can be split into two parts:
- adding complex types into zokrates : we merged the infrastructure for this into develop so we can soon start adding better types and exposing them to the user. First candidates are uint32 and associated operations to reduce verbosity, structs would be further down the road. Suggestions welcome! 
- defining an ABI to call zokrates functions, possibly with json

**Comment by fleupold** [comment]
+1 that this would be nice to have. 

Until then, you might be able to use the `--interactive` flag and pipe in the list of private variables (separated by newline) from a file like

```
./zokrates compute-witness --interactive < data.input
```

**Comment by Schaeff** [comment]
I discussed this with @HarryR and we'd welcome contributions on this as it looks pretty self-contained. How about a first version of this to only accept a JSON array like https://github.com/JacobEberhardt/ZoKrates/blob/develop/zokrates_cli/tests/code/simple_add.arguments.json before we look at a more advanced ABI? I think it would solve @fleupold's issue for now and we can refine later.

**Comment by Howlla** [comment]
genuinely interested in implementing this for a project im working on
Could someone guide me on how I should start?

**Comment by Schaeff** [comment]
Hey @Howlla, sorry for the delay here, we're going to do some design work on this, if you're still interested in helping with implementation that would be welcome!

**Comment by xonack** [comment]
Hi all, I'm trying to use ABI as input format in the CLI but am getting the following output:
 `$ zokrates compute-witness --abi --verbose -i compute -s abi.json                                                            ⏎
Computing witness...
ABI input as inline argument is not supported. Please use --stdin.`

This seems to go contrary to the docs, is this expected? If so, how would I go about taking advantage of ABI inputs?

Cheers

**Comment by alv-around** [comment]
> Hi all, I'm trying to use ABI as input format in the CLI but am getting the following output: `$ zokrates compute-witness --abi --verbose -i compute -s abi.json ⏎ Computing witness... ABI input as inline argument is not supported. Please use --stdin.`
> 
> This seems to go contrary to the docs, is this expected? If so, how would I go about taking advantage of ABI inputs?
> 
> Cheers

@xonack this works for me fine:

```
$ zokrates compute-witness --abi --stdin < sample.json
```
