### ISSUE TITLE
Internal error: entered unreachable code with `--isolate-branches`

### ISSUE THREAD

**Issue by axic** [Zokrates/ZoKrates#1056]
It happens on this branch and I don't have the time to reduce to a smaller example: https://github.com/axic/zkoisc/tree/field. It doesn't happen on the `master` branch of the repo.

The binary used is the release version of 0.7.8 for aarch64-darwin.

```sh
% zokrates compile --isolate-branches -i oisc.zok                   
Compiling oisc.zok

internal error: entered unreachable code (zokrates_core/src/flatten/mod.rs:1041:30)
This is unexpected, please submit a full bug report at https://github.com/Zokrates/ZoKrates/issues
```

(This may be related to #891)

**Comment by dark64** [comment]
Hello @axic, thanks for the report! I've successfully reduced the code and identified the bug.

**Comment by dark64** [comment]
Closing this, this issue is no longer present on the develop branch.
