### ISSUE TITLE
Witness computation disagrees between binary and js module

### ISSUE THREAD

**Issue by 0xpApaSmURf** [Zokrates/ZoKrates#1096]
## Description

Computing a witness using the binary succeeds whilst performing the same witness computation using `zokrates-js` fails.

This seems to be inconsistent behaviour between the `zokrates` binary and the `zokrates-js` library.

## Environment

- Compiler version: `zokrates: 0.7.11`, `zokrates-js: 1.0.39`
- Operating system: macOS 11.3.1

## Steps to Reproduce

Using the `0.7.11` docker image binary and `1.0.39` of `zokrates-js`.

```
// test.zok
import "hashes/sha3/256bit" as sha3

def main(u64 currentTime, private u64[4] expected) -> u64[4]:
    u64[4] h = sha3([currentTime])
    assert(h[0] == expected[0])
    assert(h[1] == expected[1])
    assert(h[2] == expected[2])
    assert(h[3] == expected[3])
    return h
```

```bash
$ zokrates compile -i test.zok
$ zokrates setup
$ zokrates compute-witness -a 1643823900 16213210585803108009 8295259912202483971 10491929171841072598 9200200322684122894
Computing witness...
Witness file written to 'witness'
$ zokrates generate-proof
Generating proof...
WARNING: You are using the G16 scheme which is subject to malleability. See zokrates.github.io/toolbox/proving_schemes.html#g16-malleability for implications.
Proof written to '/local/proof.json'
```

Witness computation and then proof generation succeeds using the `zokrates` binary in the `0.7.11` docker container.

Then in `zokrates-js`:

```javascript
initialize().then((provider) => {
    const source = 'import "hashes/sha3/256bit" as sha3             \n \
        \n \
    def main(u64 currentTime, private u64[4] expected) -> u64[4]: \n \
            u64[4] h = sha3([currentTime]) \n \
            assert(h[0] == expected[0]) \n \
            assert(h[1] == expected[1]) \n \
            assert(h[2] == expected[2]) \n \
            assert(h[3] == expected[3]) \n \
            return h'

    const artifacts = provider.compile(source);
    const { witness, output } = provider.computeWitness(artifacts, ['1643823900', ['16213210585803108009', '8295259912202483971', '10491929171841072598', '9200200322684122894']]);
    // Execution failed: Assertion failed at main.zok:5:18
})
```

Passing in the exact same witness to the javascript library causes it to fail on the first assertion line even though the witness computation was done successfully using the same circuit on the binary.
-->

**Comment by dark64** [comment]
Hey @0xpApaSmURf, thanks for the report! We found the underlying issue, it looks like the `u64` inputs are stripped in the encoding process because of the rogue `as usize` cast (it is `u32` in wasm). This means that  `16213210585803108009` is encoded to `0x000000006365aea9` instead of `0xe100e5206365aea9`, which makes the assertion fail. We have a working fix already and will land in the next release soon.
