### ISSUE TITLE
Support return array dimension based on generic parameter

### ISSUE THREAD

**Issue by sshravan** [Zokrates/ZoKrates#1105]
## Description
Would it be possible to support return values of a function based on generic parameter?
For instance, in the example below the dimension of the array returned by ```fancy_duplicate``` will be known at compile time.
## Environment

- Compiler version: 0.7.9 (048221ba)
- Operating system: Ubuntu

## Steps to Reproduce

```zokrates
def fancy_duplicate<N>(bool[N] bits) -> bool[2*N]: // This line throws an error
    bool[2*N] output = [false; 2*N] // This line works
    // for u32 i in 0..N do
    //     output[2*i+1] = bits[i]
    // endfor
    return output

def main(bool[16] input) -> bool:
    bool[32] output = fancy_duplicate(input)
    assert(output == [false; 32])
    return true

```

**Comment by sshravan** [comment]
Of course, by making ```fancy_duplicate<N, M>(bool[N] bits) -> bool[M]```, it is possible to circumvent this obstacle at the cost of checking ```M == 2*N```. However, it doesn't seem to be the cleanest way to do this.

**Comment by Schaeff** [comment]
Yes that is the preferred approach at this point. I assume by "cost" you are not referring to prover cost here, which is not impacted.
