### ISSUE TITLE
Documentation of `verifyEddsa.zok` test

### ISSUE THREAD

**Issue by mark-moir** [Zokrates/ZoKrates#1106]
https://github.com/Zokrates/ZoKrates/blob/656923c601bdb9d249d8c372ea962c407274c658/zokrates_stdlib/tests/tests/signatures/verifyEddsa.zok#L4

says that code to produce the test case is in the `pycrypto` repo.  I can find and successfully use the code to create keys, sign a message and verify the signature.  However, I cannot find anywhere specific values to produce exactly the example in this test.  I would like to be able to do so, in order to better understand the relationship between keys, signatures, and `verifyEddsa`.

Also, I believe:

https://github.com/Zokrates/ZoKrates/blob/656923c601bdb9d249d8c372ea962c407274c658/zokrates_stdlib/tests/tests/signatures/verifyEddsa.zok#L10

should say "Public key", not "Private key", right?

**Comment by Schaeff** [comment]
Correct! Good spot!
