### ISSUE TITLE
Do I have to upload a verifier for each input/output set that I want valid? Is there sample code for that?

### ISSUE THREAD

**Issue by ddengster** [Zokrates/ZoKrates#1110]
```
def main(private field a, field b) -> (field):
  field result = if a * a == b then 1 else 0 fi
  return result  
```

If I want more than 1 input/output set to be valid, ie. `a = 0, b =0, output=1`, `a=1, b=1, output=1`, `a=2, b=15, output=0`, it seems I'd have to upload a verifier for each one. Is there something in cryptography that describes this behaviour?

Ofc, I'd have to pay gas for each of these contracts.

**Comment by dark64** [comment]
No, that would be very impractical. The order of operation would be something like this:

- Compile the program
- Run the setup to generate the keys
- Export the verifier and deploy it

Then you can do the following as many times as you want:

- Run the computation (witness computation)
- Generate the proof of computation
- Give the proof to the contract to verify it (you can also verify natively without the contract using the CLI)

Hope it make sense. Keep in mind that each time you change the code of the program you need to recompile, run the setup and export a new verifier.

Also have a look at #995

**Comment by ddengster** [comment]
Thanks, I figured out what went wrong. Simply put I was running the setup to generate the keys each time I ran the compute witness step.

```
zokrates compile -i root.zok
zokrates setup
zokrates export-verifier -o ../contracts/verifier.sol
```

```
zokrates compute-witness --verbose -a 2 4
## zokrates setup #do not do this!
zokrates generate-proof
zokrates verify
# use proof.json as input to verifyTx; it should return true
```

**Comment by Schaeff** [comment]
Closing this as it looks resolved. Feel free to reopen if not @ddengster
