### ISSUE TITLE
Using imported libraries in zokrates.js

### ISSUE THREAD

**Issue by newtsjamie** [Zokrates/ZoKrates#1115]
Hi. 

Looking for guidance on using imports within Javascript bindings like sha256packed in this example: 

```
const { sha256packed } = require("hashes/sha256/512bitPacked");

initialize().then((zokratesProvider) => {
  const source =
    "def main(private field birthYear, private field rand1, private field rand2, field hash1, field hash2) -> (field):n" +
    "    field[2] h = sha256packed([0, birthYear, rand1, rand2])\n" +
    "    return (h[0] == hash1 && h[1] == hash2) ? 1 : 0";
```

Very interested to know if this is possible and if not what you're suggested workaround might be. Many thanks.

**Comment by dark64** [comment]
Hello @jammydodga1, zokrates.js contains a packed stdlib so you can just import normally in the zokrates source code like so

```zokrates
import "hashes/sha256/512bitPacked" as sha256packed
```

If you just need to import stdlib functions, you do as above. For other modules you might have in your project, you need to provide a resolver callback, which is explained [here](https://zokrates.github.io/toolbox/zokrates_js.html#compilesource-options).

Let me know if you have any other questions or if this fixed your issue.

**Comment by newtsjamie** [comment]
This worked. Thanks a lot :)

**Comment by supertestnet** [comment]
is there a version of the standard libraries available for use in the browser alongside [the cdn-delivered package](https://zokrates.github.io/toolbox/zokrates_js.html#cdn)? Import statements usually don't work in the browser because the import keyword is undefined, and even if it was defined I think I would need to point to the file "hashes/sha256/512bitPacked.js" which must be hosted online somewhere

**Comment by dark64** [comment]
> is there a version of the standard libraries available for use in the browser alongside [the cdn-delivered package](https://zokrates.github.io/toolbox/zokrates_js.html#cdn)? Import statements usually don't work in the browser because the import keyword is undefined, and even if it was defined I think I would need to point to the file "hashes/sha256/512bitPacked.js" which must be hosted online somewhere

Any non-relative path that matches with the standard library module will be resolved automatically as the whole stdlib is embedded in the js module. You can import directly like so `import "hashes/sha256/512bitPacked" as hash;`.

See this gist for reference https://gist.github.com/dark64/f58a1c8f0e1a2297ba40bfe82d3772a3
