### ISSUE TITLE
zokrates-js webpack packaging/build(?) issues

### ISSUE THREAD

**Issue by ddengster** [Zokrates/ZoKrates#1116]
## Description

I'm trying to setup a simple html page launch with zokrates-js and webpack, unfortunately I'm getting (package/build?) errors on the web console. I don't get those while running `node src/index.js` however.

The web console error is:
`Uncaught (in promise) TypeError: o is not a constructor`

Probably something to do with not understanding how webpack works i think, hopefully someone can point me in the right direction.

## Environment

- Compiler version: `npm: 8.1.2`
- Operating system: Windows

## Steps to Reproduce

`src/index.js`
```
const { initialize } = require('zokrates-js/node');
initialize().then(zokratesProvider => {
  const source = "def main(private field a) -> field: return a * a";

  console.log(source);
}

```

`index.html`
```

 <!DOCTYPE html>
 <html>
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Guess the number!</title>
    
    <script src="./dist/bundle.js" defer></script>
    <!-- <script src="./app.js" defer></script> -->
  </head>
   
  <body>
  
    <h1>Guess the number!</h1>
    
  </body>
 </html> 
 
```

`package.json`
```
{
  "name": "zk_jstest",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "build": "webpack",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fs": "^0.0.1-security",
    "path": "^0.12.7",
    "webpack": "^5.71.0",
    "webpack-cli": "^4.9.2",
    "zokrates-js": "^1.0.39"
  }
}
```

`webpack.config.js`
````
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
  },
  resolve: {
    fallback: {
        "fs": false
    },
  }
};
````

**Comment by dark64** [comment]
Hi @ddengster,

You should import `zokrates-js` instead of `zokrates-js/node`, it looks like you are building for the browser environment. We have a remix plugin that uses webpack 5 for builds, have a look at the config [here](https://github.com/Zokrates/zokrates-remix-plugin/blob/master/webpack.common.js) and modify it if necessary for your needs.

**Comment by ddengster** [comment]
i couldn't get it to work, so i sidestepped the issues and used a local server instead. Thanks for the advice!
