### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#113]
Builds are slow as cargo builds three times from a fresh cache.
Speed up Jenkins by caching cargo modules.

**Comment by Schaeff** [comment]
@kyroy any thoughts on this?

**Comment by Schaeff** [comment]
Actually it seems cache does work. It's rather building which is very slow at the moment (20 seconds for a single dependency)

**Comment by Meshugah** [comment]
Hey, any guidance on how I could help with this? More detail would be appreciated!

**Comment by Schaeff** [comment]
Hey @Meshugah! I haven't looked deeply into this and maybe @kyroy can share some thoughts, but identifying areas of improvement would be a good first thing by looking at https://jenkins.kyroy.com/job/ZoKrates/view/change-requests/

**Comment by Schaeff** [comment]
While researching #147, I identified that nightly Rust is not packaged for alpine, which is a blocker as long as we use nightly features.

**Comment by Schaeff** [comment]
now that #172 is merged, we can close this
