### ISSUE TITLE
"Unknown version" running mpc verification step with docker

### ISSUE THREAD

**Issue by signorecello** [Zokrates/ZoKrates#1144]
## Description

When running the `mpc verify` step with docker, I expected to see the verification running. Instead, when running with the `latest` tag, I get the error "Unknown version". It works fine if I choose an older tag for the docker image ex. `zokrates/zokrates:0.7.11`

## Steps to Reproduce

After running the rest of the MPC steps:
```zokrates
docker run zokrates/zokrates zokrates mpc verify -i params/param -c circuits/circuit -r radix/radix
```

**Comment by Schaeff** [comment]
@dark64 is this what we discussed? If so let's rename this issue

**Comment by dark64** [comment]
Can you specify a bit more about where this error is coming from? It seems to me that this comes from docker, but I cannot seem to replicate it.

`docker run zokrates/zokrates zokrates --help` works fine for me
