### ISSUE TITLE
wrong SHA 256 values being used with Zokrates ?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [Zokrates/ZoKrates#1149]
## Description

I have been following the tutorial given by AwesomeHuang [here ](https://github.com/AwesomeHuang/Zokrates_Demo)

I am using Remix IDE on Firefox

I modified the provided code to make sure it fits syntax of the latest version of Zokrates

However, the problem seems to be the the **SHA-256 Hashes** being used in the program

I have been trying to use their given code and then adapt it to my own use case. However, while trying to test out their code, i noticed that the SHA-256 hashes they are using;

`zokrates compute-witness -a 50 1000 242738482787324818092317501628658271637 853498718274837825789312739748392789743 438758372489912996993285694393204086976`

the hashes for the values of 50 and 100 are given as 

`242738482787324818092317501628658271637
`
and 

`242738482787324818092317501628658271637
`

respectively

However, when i try to hash these numbers, i cannot get this hash. So it is the mystery on how they are getting these hash values and using them in Zokrates

Can you please clarify this

## Environment

- Compiler version: 0.7.13
- Operating system: Ubuntu 20.04

**Comment by dark64** [comment]
I'm not sure about these values but I just tested the correctness of the current implementation:

```
import "hashes/sha256/512bitPacked" as sha256packed

def main(private field value) -> (field[2]):
    field[2] result = sha256packed([0, 0, 0, value])
    return result
```

We get the following result:

```
$ zokrates compute-witness -a 50 --verbose
Computing witness...

Witness: 
["258786741933533326412793312951361072826","88795392107901394003693036759300599309"]

Witness file written to 'witness'
```

`258786741933533326412793312951361072826` => `c2b08378039e63f41c443fa0f747eeba`
`88795392107901394003693036759300599309` => `42cd5ed65cf427846c234df2f3d26e0d`

As we are using `512bitPacked` that means our input in hex to the sha256 would be

`
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000032
`

so we can compare with eg. `sha256sum`

```
$ echo 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000032 | xxd -r -p | sha256sum
c2b08378039e63f41c443fa0f747eeba42cd5ed65cf427846c234df2f3d26e0d
```

which seems correct.

**Comment by SyedMuhamadYasir** [comment]
Hi @dark64 , thanks for your descriptive reply

i just have confusion in the part where **sha256** produces purely numeric outputs - the **Witness calculation step**;

```
$ zokrates compute-witness -a 50 --verbose
Computing witness...

Witness: 
["258786741933533326412793312951361072826","88795392107901394003693036759300599309"]

Witness file written to 'witness'
```
In this part, i am confused as to how SHA256 is producing purely numeric strings, because every sha256 generator on the internet gives an **alphanumeric** string

so , for the sake of curiosity, i want to know how exactly is sha256 producing these numeric outputs

P.S : I am using zokrates in remix and i have no way to find out the correct hash to supply for the required fields, as demonstrated in AwesomeHuang's repository

**Comment by SyedMuhamadYasir** [comment]
anyone ?

**Comment by dark64** [comment]
Sha256 always produces numeric values, the only difference is in the way you are presenting those values, in ZoKrates `field` values are presented in the decimal form. If you use any decimal to hex converter you would get the following:

```
258786741933533326412793312951361072826 => c2b08378039e63f41c443fa0f747eeba
88795392107901394003693036759300599309 => 42cd5ed65cf427846c234df2f3d26e0d
```

which combined would result in a hex string `c2b08378039e63f41c443fa0f747eeba42cd5ed65cf427846c234df2f3d26e0d` that you might find as a result in the hash functions in other languages. ZoKrates doesn't have a notion of strings so everything is numeric.

**Comment by Schaeff** [comment]
Note that if you use the [ABI](https://zokrates.github.io/toolbox/abi.html), you can avoid dealing with these low level numeric values.
