### ISSUE TITLE
zokrates-js 1.0.43 drops support of bellman as the backend?

### ISSUE THREAD

**Issue by zkguru** [Zokrates/ZoKrates#1150]
Hi,

I've found that zokrates-js 1.0.43 does not use bellman as the backend, it uses Ark now. Versions prior to this one, were using bellman. So any particular reasons to drop the support of bellman? What should we do if we want to use zokrates-js with bellman in the future versions.

We encountered a problem to deserialize the proving key with zokrates-js 1.0.43, I think it should be caused by the change of backend, because our proving key was generated with backend=bellman. Let me know if I misunderstood it.

Thanks.

**Comment by dark64** [comment]
It is available again on `zokrates-js^1.1.2`
