### ISSUE TITLE
verify ECDSA signature

### ISSUE THREAD

**Issue by Jonas-Metzger** [Zokrates/ZoKrates#1155]
Is it feasible to verify ECDSA signatures in Zokrates? I would need to verify ECDSA signatures on the [P-384 curve](https://en.wikipedia.org/wiki/P-384) and unfortunately can't change it to a EdDSA curve as it is an existing system. Is there any existing implementation I could start off with?

**Comment by Schaeff** [comment]
Doing elliptic curve operations is prohibitively expensive in the flavour of snarks we support at the moment, unless you use some specific curves such as BabyJubJub which we have support for.

**Comment by open-contracts** [comment]
How long would it take to create the proof for one signature on a reasonable chip @Schaeff ? E.g. 20min would be totally fine in my application. Or are we talking hours? Days?

**Comment by Jonas-Metzger** [comment]
How long would it take to create the proof for one signature on a reasonable chip @Schaeff ? E.g. 20min would be totally fine in my application. Or are we talking hours? Days?
