### ISSUE TITLE
Any chance you could add a SHA-384 implementation?

### ISSUE THREAD

**Issue by Jonas-Metzger** [Zokrates/ZoKrates#1156]
Hi! I want to compute the SHA-384 hash of a long bytearray (~4500 bytes) using Zokrates when verifying a signature. If I understand correctly, it must be very similar to SHA-512. The closing comment of https://github.com/Zokrates/ZoKrates/issues/528 says it is 'straightforward' to get to SHA-512 from the SHA-256 implementation of the Zokrates stdlib. For me it is everything but straightforward unfortunately. Is there anyone for whom it is a less daunting task (maybe @dark64 who wrote the SHA-256 code), who'd be so kind to implement a working example? I'd be incredibly grateful!

**Comment by Schaeff** [comment]
Thanks for opening the issue. Hashing 4500bytes seems very expensive in a snark: for sha256 we are at 25k constraints for 64bytes of input, so it would cost in the order of 2 million constraints for 4500bytes. SHA-384 seems unlikely to be cheaper.
