### ISSUE TITLE
Could not export verifier with given parameters

### ISSUE THREAD

**Issue by tomsib2001** [Zokrates/ZoKrates#1178]
I have been following this (1 year old) tutorial: https://www.dailambda.jp/blog/2021-02-21-zokratez/ with Zokrates 0.7.14.

When I run the step
`zokrates setup -s g16`
I get a warning:
```shell
Performing setup...
WARNING: You are using the G16 scheme which is subject to malleability. See zokrates.github.io/toolbox/proving_schemes.html#g16-malleability for implications.
Verification key written to 'verification.key'
Proving key written to 'proving.key'
Setup completed
```
and then
`zokrates export-verifier -s g16`  doesn't recognize the option `-s g16`. If I remove it I get:
```shell
zokrates export-verifier
Could not export verifier with given parameters (curve: bls12_381, scheme: g16): not supported
```

Not being an expert in cryptography, I'm not sure if this is actually a bug; but since this command seems to have worked in the past for the blogger, I was wondering why it isn't any more?
Thanks in advance.

**Comment by dark64** [comment]
Before you had to pass the curve to the `export-verifier` command, now it is read from the verification key. In the blog example, the author is actually exporting with the wrong curve on purpose (the default curve which was set to `bn128`). I guess you can hack around this limitation by temporarily changing the `curve` field in the `verification.key` to `bn128`.
