### ISSUE TITLE
ZKP integration into dApps

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [Zokrates/ZoKrates#1191]
## Abstract

There are no guidelines on what to do with the verifier.sol once generated. There should be a proper pipeline to integrate any zero knowledge proof into a dApp

## Motivation

In all honesty, my motivation us that i am having trouble using zero knowledge proofs in my proposed dApp. Hence the request 

## Specification

This, i might not be qualified enough at the moment to comment on

**Comment by Schaeff** [comment]
Hi @SyedMuhamadYasir, can you be more precise about what you mean? The Solidity verifier can be deployed on an EVM chain and then proofs can be verified there. Check the end of [this tutorial](https://zokrates.github.io/examples/sha256example.html). If you're asking about how to design a dApp which uses zkSNARKs, this is not something ZoKrates is opinionated about as it only takes care of the zkSNARK component. For that, check out projects like [zcash](https://zips.z.cash/protocol/protocol.pdf), [nightfall](https://github.com/EYBlockchain/nightfall_3) or [tornado cash](https://github.com/tornadocash/tornado-core)

I'll close this but feel free to reopen if you have a specific improvement or issue in mind.

**Comment by SyedMuhamadYasir** [comment]
> Hi @SyedMuhamadYasir, can you be more precise about what you mean? The Solidity verifier can be deployed on an EVM chain and then proofs can be verified there. Check the end of [this tutorial](https://zokrates.github.io/examples/sha256example.html). If you're asking about how to design a dApp which uses zkSNARKs, this is not something ZoKrates is opinionated about as it only takes care of the zkSNARK component. For that, check out projects like [zcash](https://zips.z.cash/protocol/protocol.pdf), [nightfall](https://github.com/EYBlockchain/nightfall_3) or [tornado cash](https://github.com/tornadocash/tornado-core)
> 
> I'll close this but feel free to reopen if you have a specific improvement or issue in mind.

Hi @Schaeff 

thanks for the clarification , appreciated ! 

the projects you listed are all quite good, but they are rather difficult to adapt for a multi-faceted project ( say if you're working on use case 'x' and want to integrate something like zcash , it is not as straightforward as it seems )

some have rather difficult documentation ( like AZTEC )

and most don't support python ( which is a shame considering how popular web3.py is )

similar to how we can spin up a wholly private blockchain in ganache and play around with it, if something along the lines of that could be added to Zokrates (e.g an small blockchain infrastructure with private transactions secured with ZK ) it would really enhance the usability and utility of Zokrates 

The most relevant suggestion to realize private transactions in ethereum was [to change the source code of an ethereum client (Geth) itself ](https://ethereum.stackexchange.com/questions/130732/how-to-integrate-zokrates-proof-into-ethereum-transactions?noredirect=1#comment152084_130732)

this is tedious considering if one does not know Golang, which is used to write geth.

if Zokrates can make private use cases easier to realize, albeit in a toy-sized manner, i don't see why it should not be part of this comprehensive zk toolbox 

cheers !
