### ISSUE TITLE
MalformedVerifyingKey (zokrates_ark/src/groth16.rs:84:56)

### ISSUE THREAD

**Issue by shishirhome** [Zokrates/ZoKrates#1207]
Hi Team

Trying this example - https://zokrates.github.io/examples/sha256example.html and receiving the below error:

`Performing verification...
called `Result::unwrap()` on an `Err` value: MalformedVerifyingKey (zokrates_ark/src/groth16.rs:84:56)`

DSL for generating Proof:

`import "hashes/sha256/512bitPacked" as sha256packed;

def main(private field a, private field b, private field c, private field d) -> bool {
    field[2] h = sha256packed([a, b, c, d]);
    assert(h[0] == 263561599766550617289250058199814760685);
    assert(h[1] == 65303172752238645975888084098459749904);
    return true;
}`

**Comment by dark64** [comment]
Can you share on which compiler version this occurs and the verification key so we can examine in depth why it's malformed. It would also be helpful to share reproducible steps that end in this error.

**Comment by shishirhome** [comment]
Hi Darko, it got sorted, I was passing in the wrong number of private inputs. Thanks for your reply.
