### ISSUE TITLE
if statements failing when using snarkjs

### ISSUE THREAD

**Issue by IlyasRidhuan** [Zokrates/ZoKrates#1214]
## Description

Zokrates circuits involving `if` statements are incorrectly failing when proofs are generated and verified using `snarkjs`
## Environment

- Compiler version: 0.8.0
- snarkjs version: 0.4.24
- ZoKrates-js version: 1.1.1
- Operating system: Mac (M1) also tested on ubuntu

## Steps to Reproduce

1. Create `testIf.zok` (a modification of the basic preimage example) file as below
```
def main(private field a, field b) {
    bool check = if (a == 0){ true} else {a * a == b};
    assert(check);
    return;
}
```
2. Compile with zokrates (using `r1cs` output) `zokrates compile -i testIf.zok`
3. Perform setup with snarkjs - [here](https://docs.circom.io/getting-started/proving-circuits/#powers-of-tau)
4. Compute witness in ZoKrates (generating circom `.witness` file) `zokrates compute-witness -a 337 113569`
5. Use snarkjs prove to generate `proof.json` - [here](https://docs.circom.io/getting-started/proving-circuits/#generating-a-proof)
6. Verifying with snarkjs fails with `[ERROR] snarkJS: Invalid proof`

Note that using ZoKrates instead of snarkjs for all the key setup and proof generation steps yields a passing proof.

**Comment by Schaeff** [comment]
Thanks for reporting this we're on it

**Comment by Schaeff** [comment]
Update: the issue seems to be that there is a disconnect between how the circom signals are allocated in the r1cs file and the ordering of the values in the wtns file.

**Comment by IlyasRidhuan** [comment]
Thanks for the quick fix!
