### ISSUE TITLE
Install script failing in certain areas of the world

### ISSUE THREAD

**Issue by partylikeits1983** [Zokrates/ZoKrates#1219]
The install script does not work in certain countries: curl -LSfs get.zokrat.es | sh 

The get.zokrates.es server is located at 162.255.119.220 in Atlanta, GA, and is denying users from certain jurisdictions.

**Comment by Schaeff** [comment]
Hi, you can find the install script on Github here

https://github.com/Zokrates/ZoKrates/blob/develop/scripts/one_liner.sh
