### ISSUE TITLE
support bellman backend in zokrates-js

### ISSUE THREAD

**Issue by zhfnjust** [Zokrates/ZoKrates#1227]
can we support bellman backend in `zokrates-js`? I don't think it's implemented right now

**Comment by dark64** [comment]
Hey @zhfnjust, it is supported, you need to set it through the options, see here https://zokrates.github.io/toolbox/zokrates_js.html#withoptionsoptions

Make sure you use `zokrates-js^1.1.3`, which is the latest version as of writing this.

**Comment by zhfnjust** [comment]
it's ok now
