### ISSUE TITLE
The Internal Algorithm behind Zokrates

### ISSUE THREAD

**Issue by zubayr1** [Zokrates/ZoKrates#1231]
HI, 
I am studying Zokrates for my thesis.
I would really appreciate if I get some links that can explain the algorithms behind Zokrates.
Like how the Verification_key, proof.json are created, the logic behind the verifier.sol.

**Comment by Schaeff** [comment]
Hi @zubayr1, ZoKrates can be seen as a front end for proving schemes listed [here](https://zokrates.github.io/toolbox/proving_schemes.html#schemes). It generates an R1CS output which is then passed as an input to the proving scheme. We link to the publication introducing each scheme, as well as to the specific implementations of these proof systems which are used in ZoKrates. We suggest you have a look at [the groth16 implementation in ark](https://github.com/arkworks-rs/groth16).
