### ISSUE TITLE
Can prove key deserialization be optimized?

### ISSUE THREAD

**Issue by p0vidl0** [Zokrates/ZoKrates#1238]
Thanks for great library.
For a custom use-case, serialized prove key have size about 29332912 bytes. The key deserialization takes 26 seconds and proof generation takes less than 2 seconds.

Please advise, is it possible in theory to optimize the [deserialization process](https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_ark/src/gm17.rs#L57) to make overall process faster?

**Comment by Schaeff** [comment]
Hi, thanks for flagging. We would welcome contributions on this.

**Comment by dark64** [comment]
> Thanks for great library. For a custom use-case, serialized prove key have size about 29332912 bytes. The key deserialization takes 26 seconds and proof generation takes less than 2 seconds.
> 
> Please advise, is it possible in theory to optimize the [deserialization process](https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_ark/src/gm17.rs#L57) to make overall process faster?

I'm closing this for now as I could not replicate the same issue with the latest version. My assumption is this issue is resolved since `0.8.1`, the issue was related to a call to the deserialization function that had validity checks which were time-consuming.
