### ISSUE TITLE
mimc7 hash algorithm bug

### ISSUE THREAD

**Issue by hotaru57** [Zokrates/ZoKrates#1316]
## Description
When i use mimc7 hash algorithm `mimc7::<91>` , i get an incorrect output

There is a constant `field[] C` in file **mimc7.zok**, the value should be `13602139229813231349386885113156901793661719180900395818909719758150455500533` when index is 91

## Environment

- Compiler version: 0.8.7

- Operating system: CentOS 7

## Steps to Reproduce
```
def main(field x, field k) -> field {
    h = mimc7::<91>(x, k);
    return h;
}
```

**Comment by dark64** [comment]
Hi @hotaru57, nice catch! 

Fixed in https://github.com/Zokrates/ZoKrates/pull/1317
