### ISSUE TITLE
Unable to initialize zokrates provider using zokrates-js

### ISSUE THREAD

**Issue by spencer-coti** [Zokrates/ZoKrates#1335]
## Description

Unable to initialize ZoKrates provider using zokrates-js

## Environment

- Operating System: Mac
- NodeJS version: 20.4.0

## Steps to Reproduce

package.json:

```
{
  "dependencies": {
    "zokrates-js": "^1.1.8"
  }
}
```

test.js (using dynamic import):

```
const main = async () => {
    let { initialize } = await import("zokrates-js");
}

main()
```

Output:
```
globalThis.crypto = webcrypto;
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
```

test.mjs (notice file extension):

```
import { initialize } from "zokrates-js";

const main = async () => {
    console.log('hello')
}

main()
```

Output:
```
globalThis.crypto = webcrypto;
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
```

**Comment by spencer-coti** [comment]
I was able to solve this by switching to NodeJS v16.16.0

**Comment by dark64** [comment]
Thanks for reporting this @spencer-coti! 
Fixed in https://github.com/Zokrates/ZoKrates/pull/1338
