### ISSUE TITLE
could not compile `zokrates_cli` (bin "zokrates")

### ISSUE THREAD

**Issue by hyh88384092** [Zokrates/ZoKrates#1348]
jerry@jerry-virtual-machine:~/ZoKrates$ cargo build -p zokrates_cli --release
   Compiling zokrates_cli v0.8.7 (/home/jerry/ZoKrates/zokrates_cli)
error: could not compile `zokrates_cli` (bin "zokrates")

Caused by:
  process didn't exit successfully: `/home/jerry/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name zokrates --edition=2018 zokrates_cli/src/bin.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=243 --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="ark"' --cfg 'feature="bellman"' --cfg 'feature="bellperson"' --cfg 'feature="default"' --cfg 'feature="zokrates_ark"' --cfg 'feature="zokrates_bellman"' --cfg 'feature="zokrates_bellperson"' -C metadata=1915016c5cc70fac -C extra-filename=-1915016c5cc70fac --out-dir /home/jerry/ZoKrates/target/release/deps -L dependency=/home/jerry/ZoKrates/target/release/deps --extern blake2=/home/jerry/ZoKrates/target/release/deps/libblake2-1523b07e48152cfd.rlib --extern byteorder=/home/jerry/ZoKrates/target/release/deps/libbyteorder-ea58b8b5a1d261bd.rlib --extern cfg_if=/home/jerry/ZoKrates/target/release/deps/libcfg_if-e585b5414182f931.rlib --extern clap=/home/jerry/ZoKrates/target/release/deps/libclap-44ad4f00948169cc.rlib --extern dirs=/home/jerry/ZoKrates/target/release/deps/libdirs-e4cb4cb17c41e638.rlib --extern env_logger=/home/jerry/ZoKrates/target/release/deps/libenv_logger-f69fbb6b3ed4924f.rlib --extern hex=/home/jerry/ZoKrates/target/release/deps/libhex-76cceba5acf8a9fa.rlib --extern lazy_static=/home/jerry/ZoKrates/target/release/deps/liblazy_static-7b70fbdb8bbfe33f.rlib --extern log=/home/jerry/ZoKrates/target/release/deps/liblog-a6fc366c64bb2139.rlib --extern rand_0_4=/home/jerry/ZoKrates/target/release/deps/librand-c3d87057c33e6671.rlib --extern rand_0_8=/home/jerry/ZoKrates/target/release/deps/librand-863c4360b3e3d4a7.rlib --extern regex=/home/jerry/ZoKrates/target/release/deps/libregex-0a817197193b0618.rlib --extern serde=/home/jerry/ZoKrates/target/release/deps/libserde-614dea5a43b44a1c.rlib --extern serde_cbor=/home/jerry/ZoKrates/target/release/deps/libserde_cbor-4817676e43d59aac.rlib --extern serde_json=/home/jerry/ZoKrates/target/release/deps/libserde_json-ca0f3a31dbbd080d.rlib --extern sha2=/home/jerry/ZoKrates/target/release/deps/libsha2-4c399d2f17202f7c.rlib --extern typed_arena=/home/jerry/ZoKrates/target/release/deps/libtyped_arena-c8ef2039799f56d1.rlib --extern zokrates_abi=/home/jerry/ZoKrates/target/release/deps/libzokrates_abi-dcfb84cf18eb008a.rlib --extern zokrates_ark=/home/jerry/ZoKrates/target/release/deps/libzokrates_ark-1a54396d1042a36a.rlib --extern zokrates_ast=/home/jerry/ZoKrates/target/release/deps/libzokrates_ast-ab5c885dcefa6ddf.rlib --extern zokrates_bellman=/home/jerry/ZoKrates/target/release/deps/libzokrates_bellman-4e25a83f7c93c782.rlib --extern zokrates_bellperson=/home/jerry/ZoKrates/target/release/deps/libzokrates_bellperson-153e36bfd964b2fd.rlib --extern zokrates_circom=/home/jerry/ZoKrates/target/release/deps/libzokrates_circom-8956f416a1b89d4a.rlib --extern zokrates_common=/home/jerry/ZoKrates/target/release/deps/libzokrates_common-4bb8c8e71b41949f.rlib --extern zokrates_core=/home/jerry/ZoKrates/target/release/deps/libzokrates_core-5eeb2b24ef4d6f8e.rlib --extern zokrates_embed=/home/jerry/ZoKrates/target/release/deps/libzokrates_embed-72066e399f9c48bd.rlib --extern zokrates_field=/home/jerry/ZoKrates/target/release/deps/libzokrates_field-89e30db5028649cf.rlib --extern zokrates_fs_resolver=/home/jerry/ZoKrates/target/release/deps/libzokrates_fs_resolver-3ca25fbff2c5cc4b.rlib --extern zokrates_interpreter=/home/jerry/ZoKrates/target/release/deps/libzokrates_interpreter-5cdd25779429a1e9.rlib --extern zokrates_profiler=/home/jerry/ZoKrates/target/release/deps/libzokrates_profiler-ab254c5931bf3123.rlib --extern zokrates_proof_systems=/home/jerry/ZoKrates/target/release/deps/libzokrates_proof_systems-9ea664439e9defca.rlib -L native=/home/jerry/ZoKrates/target/release/build/blst-ce3d381fd13719a9/out -L native=/home/jerry/ZoKrates/target/release/build/pasta-msm-d0878104742f4acb/out -L native=/home/jerry/ZoKrates/target/release/build/semolina-57172d838222e048/out` (signal: 9, SIGKILL: kill)

**Comment by dark64** [comment]
@hyh88384092 Can you check RAM usage? It might be an out-of-memory issue on your side. You can increase your swap space as a quick solution.
