### ISSUE TITLE
ABI input not supported

### ISSUE THREAD

**Issue by ssolit** [Zokrates/ZoKrates#1357]
Hi All, 

I am trying to use a json input, but I am getting the error "ABI input as inline argument is not supported. Please use `--stdin`. It looks like a similar issue was reported here: https://github.com/Zokrates/ZoKrates/issues/105#issuecomment-1279227180. Was this ever addressed?

Thanks

**Comment by alv-around** [comment]
@ssolit  this works for me fine:

```
$ zokrates compute-witness --abi --stdin < sample.json
```

**Comment by dark64** [comment]
@alvaro-alonso gave a correct usage example, closing this for now 👍
