### ISSUE TITLE
wrong feature coverage in zokrates_ast

### ISSUE THREAD

**Issue by brew0722** [Zokrates/ZoKrates#1365]
The `flat_expression_from_variable_summands` function is also used within the `snark_verify_bls12_377` function implemented with the **ark** feature.
https://github.com/Zokrates/ZoKrates/blob/f10293338160eee2209e62f536bea8f095ce38dd/zokrates_ast/src/common/embed.rs#L499

https://github.com/Zokrates/ZoKrates/blob/f10293338160eee2209e62f536bea8f095ce38dd/zokrates_ast/src/common/embed.rs#L26
However, since the **use** expression is tied to the **bellman** feature, a compilation error occurs if only the **ark** feature is activated.

**Comment by dark64** [comment]
Nice catch 😅 Thanks @brew0722

**Comment by brew0722** [comment]
@dark64 Thanks for your quick confirmation 👍 , I'll be waiting.
