### ISSUE TITLE
associativity of subtraction of field values with function calls is wrong

### ISSUE THREAD

**Issue by aspiers** [Zokrates/ZoKrates#167]
This is best demonstrated by a test case:

```
def x() -> (field):
  return 3

def main() -> (field):
  // These all work
  7 == 10 - x()
  8 == 10 + 1 - x()
  8 == 10 - 3 + 1
  8 == (10 - 3) + 1
  8 == (10 - x()) + 1
  8 == 10 - (x() - 1)

  // These are wrong
  8 == 10 - x() + 1
  6 == 10 - x() - 1

  return 1
```

All of these assertions should pass; however the final two fail:

```
setup successful: true
Computing witness for:
def main():
        7 == 7
        8 == 8
        8 == 8
        8 == 8
        8 == 8
        8 == 8
        8 == 6
        6 == 8
        return 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "Condition not satisfied: 8 should equal 6" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It seems that `10 - x() + 1` is interpreted as `10 - (x() + 1)` rather than `(10 - x()) + 1`.  I guess it's a problem with the way associativity is handled in combination with subtraction.  Taking a wild guess, maybe it's an issue with `flatten_field_expression()`?  But I never looked at Zokrates before this weekend, and only looked at the implementation for 30 minutes or so, so take that guess with a large pinch of salt ;-)

This bug was found in partnership with @GuthL, so thanks to him for being a great partner in crime :-)

**Comment by Schaeff** [comment]
Thanks for this, good spot. I'd suspect a problem in the parser, not the flattener, but not sure.

**Comment by Schaeff** [comment]
@GuthL just wondering if you made a start on this?

**Comment by GuthL** [comment]
I just had a quick look but nothing conclusive yet. What make you think it depends on the parser?

**Comment by Schaeff** [comment]
I had a crack at it as it's not a trivial piece of our codebase, maybe not the best to get started..

**Comment by GuthL** [comment]
FIne with it! Could you explain how the bug came to be?

**Comment by Schaeff** [comment]
@GuthL Sure, I commented on the PR.

**Comment by Schaeff** [comment]
0.3.2 is out with a fix

**Comment by aspiers** [comment]
Awesome, thanks!  BTW for future issues you might enjoy this trick: https://help.github.com/articles/closing-issues-using-keywords/
