### ISSUE TITLE
Implement eWASM verifier

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#222]
We currently support Solidity as a target for the Ethereum verifier (see [here](https://github.com/Zokrates/ZoKrates/blob/f39214df65b6724544a0e50c5bea0e3862528193/zokrates_core/src/proof_system/bn128/gm17.rs#L194) and [here](https://github.com/Zokrates/ZoKrates/blob/f39214df65b6724544a0e50c5bea0e3862528193/zokrates_core/src/proof_system/utils.rs#L185)).
Implement a verifier that can work on an eWASM-enabled chain.

Suggested by @axic. I'm not exactly sure what the scope would be here: which curve? I guess we can't compile our Solidity code to ewasm?

**Comment by axic** [comment]
> I'm not exactly sure what the scope would be here: which curve?

Any curve you think makes sense. I think for starts it would be the same one supported with the Solidity code.

> I guess we can't compile our Solidity code to ewasm?

Not yet, that is still out for at least 6 months.

**Comment by axic** [comment]
If you have the verifier written in Rust already then I'd say it can be adapted with little changes for ewasm.

**Comment by Schaeff** [comment]
Closing in favor of #274
