### ISSUE TITLE
Out of bounds memory access with Identity wasm solver

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#231]
`Identity([1]) == Ok([1])` is being tested in the wasm tests but for some reason the `array_if` test in `zokrates_core` does not pass because `Identity([1])` returns `Error solving the problem: Trap: Trap { kind: MemoryAccessOutOfBounds }`
I'm probably missing a level of understanding here.
cc @gballet

**Comment by gballet** [comment]
This means that the WASM program tried to write at an invalid location, which is strange. Could you link to the actual build that had this issue?

**Comment by stefandeml** [comment]
here you go:
https://github.com/Zokrates/ZoKrates/pull/221

**Comment by Schaeff** [comment]
Closed by #263
