### ISSUE TITLE
Add compile time options to the documentation

### ISSUE THREAD

**Issue by JacobEberhardt** [Zokrates/ZoKrates#237]
Compile time flags should be documented in the ZoKrates book.
E.g., `--backend gm17` to use the GM17 snark construction.

**Comment by Schaeff** [comment]
It's [here](https://github.com/Zokrates/ZoKrates/blob/44a8764e78f1a68f6d148a5ed67e9e278b92a0e3/zokrates_book/src/reference/backends.md) but not on master yet

**Comment by Schaeff** [comment]
Closing as backends are not available on master yet so no inconsistency
