### ISSUE TITLE
Adding more cryptographic primitives to ZoKrates

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#244]
Hello everybody,

currently we are working on adding additional cryptographic primitives to ZoKrates.
The focus is on adding support for embedded elliptic curve computations (based on babyJubjub) and their applications like pedersen commitments, elliptic curve signature verification,..

Scope:
- [x] twisted edwards ECC (Addition, Doubling, scalar multiplication, group-order check, on-curve check)
- [x] montgomery ECC (Addition, Doubling, edwards2montgomery, montgomery2edwards) 
- [x] Efficient range checks for constant constraints 
- [x] Perdersen  commitments
- [x] EdDSA signature verification using SHA256

Part of a later release:
* Pedersen hashes (non-homomorphic)
* EdDSA signature verification using Pedersen hashes

Current progress can be tracked here:
https://github.com/Zokrates/ZoKrates/tree/add-cryptolib

**Comment by 3psil0n** [comment]
Hey, I just want to let you know that I think additional primitives are really important for "bringing ZoKrates to the application world"

**Comment by stefandeml** [comment]
Hello, thanks for the feedback. We are actually working on a release of this for the next days.

**Comment by 3psil0n** [comment]
This sounds cool. Especially having at least some type of signature. This enables the implementation of "cool" identity schemes using ZoKrates :) 
Im really looking foward to this new features.

**Comment by stefandeml** [comment]
https://github.com/Zokrates/ZoKrates/pull/301

**Comment by ronaldmannak** [comment]
@stefandeml is there any ETA on the Pedersen hash?
