### ISSUE TITLE
Improve memory management for FFI calls between ZoKrates and libsnark

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#248]
Hello everybody,

the existing FFI implementation is not ideal.
Buffer-overflow and memory leakage problems are fixed in this PR: https://github.com/Zokrates/ZoKrates/pull/221

However, the new implementation for releasing memory is still not very clean. Ideally the memory would be allocated in Rust such that we don't have to manage the memory on the cpp side.

Happy to provide more details if necessary.

**Comment by stefandeml** [comment]
this will be fixed by this issue: https://github.com/Zokrates/ZoKrates/issues/256

**Comment by Schaeff** [comment]
Do you mean #258

**Comment by stefandeml** [comment]
Can be closed as we now import gadgets via Rust.
Integration with the backend is out of scope of this issue.
