### ISSUE TITLE
Add support for hex literals

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#253]
Would be nice to have some support for hex literals to make declarations like the following less verbose:
`field[32] h0 = [0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1]`
could be something like:
`field[32] h0 = hex!("0x6a09e667")`

**Comment by Schaeff** [comment]
Can this wait for integer types?
