### ISSUE TITLE
Feature request: UX - 'progress bar'

### ISSUE THREAD

**Issue by iAmMichaelConnor** [Zokrates/ZoKrates#292]
I know this is a classically difficult problem in computer science, but is there a way to relay to users how far through the 'compute-witness' or 'generate-proof' computation they are?
With proofs sometimes taking minutes, it would be nice to be able to estimate time-to-completion.

**Comment by Schaeff** [comment]
I'm not sure this would be the best use of time at this point. `compute-witness` should be instant, though!
