### ISSUE TITLE
constant propagation for imports fails

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#307]
> ecc/edwardsAdd.code

```
def main(field[2] pt1, field[2] pt2, field[10] context) -> (field[2]):
    field a = context[0]
    field d = context[1]

    field u1 = pt1[0]
    field v1 = pt1[1]
    field u2 = pt2[0]
    field v2 = pt2[1]

    field uOut = (u1*v2 + v1*u2) / (1 + d*u1*u2*v1*v2)
    field vOut = (v1*v2 - a*u1*u2) / (1 - d*u1*u2*v1*v2)

    return [uOut, vOut]
```

and a version wrapped with defined `context`: 
```
import "ecc/edwardsAdd.code" as add
import "ecc/babyjubjubParams.code" as context

def main(field[2] pt1, field[2] pt2) -> (field[2]):
	context = context()

	field[2] out = add(pt1, pt2, context)

	return out
```

results in equal number of constraints: 

> Number of constraints: 23

The second version should have less constraints as `context` only holds constants and as a result we should several multiplications for free

**Comment by Schaeff** [comment]
Can it be reduced to
```
import foo
def main() -> ():
   // use foo somehow
```
vs
```
def foo() -> ():
   // body
def main() -> ():
   // use foo somehow
```
having different # of constraints or did I misunderstand?

**Comment by stefandeml** [comment]
not sure if I'm following, but in both examples const propagation should reduce the number of constraints if `foo` just defines constants (like `context` in our case) for the `main` function

**Comment by Schaeff** [comment]
cf #357
