### ISSUE TITLE
Switch IR implementation of LinComb from map to vec

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#312]
We represent a linear combination as a Map where the key is a variable and the value is the coefficient for that variable. This is intuitive, but operations are expensive as we need to reduce each variable to a single record, which requires iterating on `a` and `b` to get `a + b`

If we used `Vec<(Variable, Coefficient)>`, LinComb arithmetics are reduced to array concatenation. We basically allow `a + a + a` where with map we would reduce to `3a`
.

We could always cheaply reduce to Map from that non-reduced representation if needed.

**Comment by pawanjay176** [comment]
Interested in working on this. What are the relevant files I should look at?

**Comment by Schaeff** [comment]
Hey @pawanjay176! Good to hear. Relevant resources are:
https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_core/src/ir/expression.rs#L39
Starting from there, the idea is to replace the map by a vector of pairs and reimplement all the traits there, simply adding to the vector.
Then here https://github.com/Zokrates/ZoKrates/blob/develop/zokrates_core/src/ir/mod.rs#L161 when converting the program into vectors to pass to libsnark, it's not unlikely that libsnark expects a "canonical" representation where each variable only appears once per vector. Not sure!

Happy to assist!

**Comment by Schaeff** [comment]
This was merged into 0.4.5
