### ISSUE TITLE
Proof of Membership Merkle Tree

### ISSUE THREAD

**Issue by drbh** [Zokrates/ZoKrates#331]
Hey ZoKraters

Great work on adding more features to the standard library! Looking forward to the addition of Pedersen hashes.

Adding the ability to easily check membership of a merkle tree by proving the path to the leaf is great way to for developers to prove that a person knows a hidden value within a larger data structure.

This could be used in many real world situations and has a high value in terms of making ZoKrates applicable to developers. Eg. Checking if a trusted certificate is in a list, checking that a user has a specified asset, a non-leaky way for a party to prove to another party they have proof a knowledge within a set.

zCash’s recent Sapling update has a _Spend Circuit_ that uses a pedersen merkle tree to check if specified values exist as leaves in the tree. [Here](https://github.com/zcash-hackworks/sapling-crypto/blob/master/src/circuit/sapling/mod.rs#L353)

**How could we build a similar merkle tree in ZoKrates DSL?**

Is it possible to build this with the existing sha256 hashes? Should we use the pedersen hash like zCash is using?

**Comment by paulperegud** [comment]
Pedersen hashes and example of membership proof with pedersen hashes ware added recently and are available in 0.4.9 version.

**Comment by Schaeff** [comment]
Hi, there are some examples [here](https://github.com/Zokrates/ZoKrates/tree/master/zokrates_cli/examples/merkleTree)
