### ISSUE TITLE
Creating VSCode plugins  for code linting 

### ISSUE THREAD

**Issue by GrandGarcon** [Zokrates/ZoKrates#335]
as  with all the programmers  today , they  are totally dependent to search the relevant function method by pressing tab for auto completion. so in case we can create the VsCODE plugin , that would be grateful.

**Comment by Schaeff** [comment]
Hey @GrandGarcon thanks for this. A first version of this will become easier once we merge #306. We're mostly talking about syntax highlighting. Do you have a plan for full IDE functionality? My intuition is that it's a lot of work and ZoKrates programs are rather small anyway so the payoff may be small?

**Comment by DhruvTheEthDeveloper** [comment]
well  for now , Syntax highlighting will be enough.  i started to read the tutorials of the vs code api present here :- https://code.visualstudio.com/api/get-started/your-first-extension.  and will try to implement in free time and also when your #306 merge is done.

**Comment by ronaldmannak** [comment]
While not as comprehensive as VSCode, [ZK Playground](https://github.com/compositeapp/ZKPlayground/releases/tag/v0.14) is custom made for ZoKrates. Feel free to try it out. All feedback welcome.

**Comment by Schaeff** [comment]
We would welcome external work on this. It became easier as we provide a grammar [here](https://github.com/Zokrates/ZoKrates/blob/master/zokrates_parser/src/zokrates.pest)
