### ISSUE TITLE
Gas Limit exceeded when verifying

### ISSUE THREAD

**Issue by zillerium** [Zokrates/ZoKrates#337]
> Gas estimation errored with the following message (see below). The
> transaction execution will likely fail. Do you want to force sending? 
> gas required exceeds allowance (6995524) or always failing transaction

Deployed contract successfully. Using remix on the Rinkeby network. Set gas limit to 7100000.

Program -

<pre>
// c0-c4 — candidates in the list, one of which not prime
// p, q — non-trivial factors for the non-prime candidate
def main(field c1, field c2) -> (field): 
  // TODO actual logic
    field c3=c1+c2
    return c3
</pre>

input - 

<pre>
{
        "proof": {
            "a": ["0x02150edc1a33c9b43af9f7f4065c1f678577661d87ec238079559d3dade4f74d", "0x1c8a3f37d1d2bb804c0bd7d3410f38ec194c7de66927167b78715789ae763c01"],
            "b": [["0x22bee54b128227589763635974e2c203cba3cd221498aa8861840ba3f16d5d7e", "0x0cef452d0a44024f96529c7a477f2116bc2b99cf5029153d1dd38b5d8a09d1e6"], ["0x28200db158548f83a066bde85aca312ba11202e38828f9dd11a45ccd91570934", "0x03705b0ac3fcecc21e75947abc8293aa70bba1226e8922faa9644b05c9367e55"]],
            "c": ["0x2ff6a6558296c58cd346eb5836afbe7546232c03a0353f0fd680a1309abf0374", "0x2b05227b0959dc0dcdddcc4686296efb0ec3aed61e4ec0706ee98dc5111099f6"]
        },
        "inputs": ["0x0000000000000000000000000000000000000000000000000000000000000001", "0x0000000000000000000000000000000000000000000000000000000000000003", "0x0000000000000000000000000000000000000000000000000000000000000004"]
    }
</pre>

**Comment by Mahsa-Bastankhah** [comment]
I have the same problem what should I do?

**Comment by zillerium** [comment]
> I have the same problem what should I do?

I have no solution yet.

**Comment by Schaeff** [comment]
What happens if you do send the transaction? This may be an issue with gas estimation?

**Comment by zillerium** [comment]
> What happens if you do send the transaction? This may be an issue with gas estimation?

I attended a ZK workshop/hackathon and a few people looked at this (including someone who works with Barry White). No one solved it and the problem was reproduced. At the present time, we are coding nodejs and sending txns via node to see what difference that makes. That work is on-going. 

We even changed the gas limit to a high figure for the VM version in Metamask and then "invalid opcode" popped up. In any case whatever is wrong here, this needs a lot more testing. 

When I get the sendTransaction done, I will push to github and then maybe others can test this.

**Comment by Schaeff** [comment]
Update on this: For those affected, for the time being try using `-s gm17` or `-s pghr13` as the issue seems to be in g16 only. Note that you'll need libsnark activated to the one-line installer won't work unfortunately. Working on a fix
