### ISSUE TITLE
want to use bls12-381 in zokrates, help needed

### ISSUE THREAD

**Issue by blackskygg** [Zokrates/ZoKrates#338]
Hi there.
 I'm currently working on a research project where we use the ZoKrates DSL to aid building complex circuits (thank you for creating such a useful tool). But the problem is that we want to use the bls12-381 curve instead of the default bn curve. I tried to replace all the occurrences of Bn256 with Bls12-381. e.g.:
```
-    use pairing::bn256::{Bn256, Fr};
+    use pairing::bls12_381::{Bls12, Fr};
...
-    type BellmanEngine = Bn256;
+    type BellmanEngine = Bls12;
```
and get it successfully compiled. However,  when trying to generate a proof for a simple circuit:
```
def main(private field a) -> (field):
    return a * a
```
with input a = 1237489271359012738947129538712093487193287419803749810273849713024871032974901327490712394370132984710,
I got the following panic:
```
thread 'main' panicked at 'assertion failed: verify_proof(&pvk, &proof, &public_inputs).unwrap()', zokrates_core/src/proof_system/bn128/utils/bellman.rs
```

According to my experiments, the program handles small inputs (with a = 3, 4, etc) quite well, so I'm suspecting that this problem is related to some hard-coded size (maybe the field size?) I'm not sure about this, so I'm here hoping to get some suggestions. What do I need to do to get ZoKrates working with bls12-381?

**Comment by blackskygg** [comment]
Changing the curve order from `21888242871839275222246405745257275088548364400416034343698204186575808495617` to `52435875175126190479447740508185965837690552500527637822603658699938581184513` seems to get the problem solved... Will close this issue if it also works for my other circuits.

**Comment by Schaeff** [comment]
Yes you're correct, we're curve specific at the moment. You can change the field size, but the backends we expose only work with bn too.
