### ISSUE TITLE
zokrates standard library - pairing

### ISSUE THREAD

**Issue by amakerofbonnetsandhoods** [Zokrates/ZoKrates#340]
Hi all,

Is there any zokrates standard library that do pairing computation? Or did anyone implement a circuit for pairings or more generally for proof verification?

Thanks,

**Comment by Schaeff** [comment]
Hey @amakerofbonnetsandhoods very good question. As far as I know, bn128 does not offer a pairing friendly embedded curve, so implementing a pairing check would be very expensive. This becomes reasonable with curves and constructs such as the ones described [here](https://eprint.iacr.org/2014/595.pdf) or more recently [here](https://eprint.iacr.org/2018/962.pdf)

These are currently not supported in ZoKrates (nor Ethereum) but are worth looking into.

cc @stefandeml feel free to chime in here

**Comment by amakerofbonnetsandhoods** [comment]
Hi @Schaeff , bn128 does not offer a cycle of pairing-friendly elliptic curves as proved [here](https://arxiv.org/pdf/1803.02067.pdf) but one can construct a 2-chain of pairing-friendly elliptic curves over bn128 via cocks-pinch method as done in zexe. The problem is not about pairing but rather the low 2-adicity of bn128 field size. More generally, did anyone try to implement a pairing in zokrates regardless of the curve?

**Comment by Schaeff** [comment]
I'm not aware of any efforts but @stefandeml may know better.

**Comment by stefandeml** [comment]
Hello @amakerofbonnetsandhoods,

I think you might mixing things up here a bit. Cocks-Pinch (CP) allows you to set up a bounded recursion for an existing curve. Hence, with CP you can construct the "outer" curve efficiently. This also has been done by the zexe team: they started with BLS377, the embedded curve, and then use CP to construct the host curve.
I'm also not sure why the 2-adicity of the bn128 field should matter, as this is the curve we use in the proof system. Hence, the prime-order subgroup needs high 2-adicity for efficient computation.

Consequently, we haven't implemented parings (miller loop) in ZoKrates yet.
However, we are currently working on making ZoKrates generic over the curve. After having done this work, adding support for pairing ECC could be interesting.

For more infos also check out this blog covering that topic:
https://medium.com/p/8e4c4bc0cc65

I will close this for now. Feel free to comment and then we can re-open the issue.

**Comment by amakerofbonnetsandhoods** [comment]
Hello @stefandeml,

The "outer" curve you construct via cocks-pinch method or else will have a subgroup order equal to the field size of the "inner" curve (i.e. BLS12-377 in Zexe for instance). Hence, the inner curve should have a high 2-adicity with respect to both the subgroup order and the field size which not the case of the BN128.
