### ISSUE TITLE
Malleability warning

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [Zokrates/ZoKrates#350]
Hi.as mentioned here `https://zokrates.github.io/reference/proving_schemes.html#g16-malleability`
usage of an ethereum address as a public input to the program solves malleability issue. how? 
if any prover has to provide a unique number as public number does this solve the problem too?

**Comment by Schaeff** [comment]
You can make your smart contract only accept proofs from a given address, so that having a proof is not enough, you need to know a private key. Yes your second suggestion is a nullifier, and you keep track of previously revealed nullifiers in the smart contract.
