### ISSUE TITLE
“thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value” while using “ZoKrates” in docker

### ISSUE THREAD

**Issue by tripteshb** [Zokrates/ZoKrates#351]
I am using "ZoKrates"(0.4.6) toolbox in "docker"(18.09.2) at Ubuntu 18.04 , while compiling a code I got the following :

zokrates@ff141f88fb6d:~$ ./zokrates compile -i test.code

thread 'main' panicked at 'called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5

note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.

I am new here, can anyone please help me to solve , thanks.

**Comment by alvaro-alonso** [comment]
@tripteshb How did you solve this problem? I am encountering the same error when running $zokrates generate-proof
