### ISSUE TITLE
Native verification

### ISSUE THREAD

**Issue by ronaldmannak** [Zokrates/ZoKrates#353]
Currently, the only way to verify the correct execution of the code is through a Solidity contract. Assuming most users are still learning ZoKrates and the concept of zk-SNARK, it might make sense to have a native verifier that can verify faster and more conveniently. A developer could verify for example using the command `./zokrates verify`

I discussed the idea at the ZK conference in Berkeley with I believe @stefandeml

**Comment by ronaldmannak** [comment]
I'm thinking of writing a ZKP introduction and tutorial. Having a built-in verifier would make it a no-brainer to use ZoKrates for that. How can we make this happen? If the issue is funding, I'd be happy to spent some time in applying for a grant.

**Comment by chrc** [comment]
Hello,
Is this issue still relevant?

**Comment by Schaeff** [comment]
Hi @chrc , this was fixed, you can check `zokrates -h`
