### ISSUE TITLE
Typo in Docs - Tutorial: Proving knowledge of a hash preimage

### ISSUE THREAD

**Issue by dakingha69** [Zokrates/ZoKrates#361]
Just went through the tutorial and noticed some small typos in the docs. In the beginning the two parties involved are `Peggy` and `Victor`. But starting in [line 101](https://github.com/Zokrates/ZoKrates/blame/master/zokrates_book/src/sha256example.md#L101) `Peggy` becomes `Alice`.

**Comment by JacobEberhardt** [comment]
One more thing:
We now use Groth16 as the default proving scheme.
The pre-image tutorial, however, is still assuming PGHR13, which shows here for example:

"ZoKrates creates a file, proof.json, consisting of the eight variables that make up the zkSNARKs proof. The verifyTx function in the smart contract deployed by Victor accepts these eight values, along with an array of public inputs. The array of public inputs consists of:"

Need to update accordingly.

**Comment by JacobEberhardt** [comment]
Addressed by #424
