### ISSUE TITLE
pghr13 or gm17 support

### ISSUE THREAD

**Issue by amakerofbonnetsandhoods** [Zokrates/ZoKrates#362]
aren't pghr13 and gm17 supported in zokrates? when running `./zokrates setup --proving-scheme pghr13` for instance, it says `Backend "pghr13" not supported`

**Comment by amakerofbonnetsandhoods** [comment]
it works with the CLI flag `-p`

**Comment by Schaeff** [comment]
They are, but only if you build from source or use the Docker image for now.
