### ISSUE TITLE
Implement no-output circuits

### ISSUE THREAD

**Issue by JustinDrake** [Zokrates/ZoKrates#389]
Boolean functions should be implementable without any "output" variables, i.e. using only assertions. Currently ZoKrates requires having one output variable for the final `return`.

**Comment by JacobEberhardt** [comment]
You can simply `return` without providing an expression.
This implies 0 outputs and no constraints.

**Comment by Schaeff** [comment]
We need to add tests before we close this

**Comment by Schaeff** [comment]
Done, closing!
