### ISSUE TITLE
proof.json missing variables ?

### ISSUE THREAD

**Issue by Mordecai71** [Zokrates/ZoKrates#408]
I've trying to generate proof.json but my file has just few variables:
{
        "proof": {
            "a": ["hex", "hex"],
            "b [["hex","hex"], ["hex", "hex"]],
            "c": ["hex", "hex"]
        },
        "inputs": ["0x01"]
}

I also tried same example at https://zokrates.github.io/sha256example.html with same result.

The documentation says "ZoKrates creates a file, proof.json, consisting of the eight variables that make up the zkSNARKs proof."

Where are the other variables ? I was expexting somethin like A, A_p, B, B_p, C, C_p, H, K.

Am I missing something ?

Sorry, I'm newbie just trying to make a Dapp work on Ethereum.

Att
Marcius

**Comment by Schaeff** [comment]
Hi @Mordecai71 by default ZoKrates uses the Groth16 scheme which is more efficient and only requires 3 curve points per proof. It is mentioned here https://zokrates.github.io/reference/proving_schemes.html. Where did you see `A, A_p, B, B_p, C, C_p, H, K`? These are PGHR13 proofs which we used in the past, would make sense to update this!

**Comment by Mordecai71** [comment]
Thank you very much. I was guessing something in that direction. Could point which Zokrates version still supports PGHR13 ? I've tried the last one (0.4.9), but it says something like "backend not supported".

Generating proof...
Backend "pghr13" not supported

Next thursday (July 4) I will presenting a demo (in classroom) with someone else software and it's still using PGHR13, so try to change this is not an option at this time.

Thank you again
--
Marcius

**Comment by Mordecai71** [comment]
Algo should be interesting update this documentation


"ZoKrates creates a file, proof.json, consisting of the eight variables that make up the zkSNARKs proof. The verifyTx function in the smart contract deployed by Victor accepts these eight values, along with an array of public inputs. The array of public inputs consists of:"

**Comment by JacobEberhardt** [comment]
Thanks for your input here!
To be able to work with pghr13, you need to build ZoKrates with `--features="libsnark"` or used the dockerized version.
I will update the docs so this is clear.

**Comment by Mordecai71** [comment]
Thank you very much.
