### ISSUE TITLE
Asserts in Validator contract

### ISSUE THREAD

**Issue by sobolev-igor** [Zokrates/ZoKrates#418]
Hi! I try using your **Verifier** contract via `call` function by another contract. Since **Verifier** uses `assert`s, such call sonsumes almost all the gas provided. Could you please replace `assert`s with `require`s to spend lass gas?

**Comment by paulperegud** [comment]
(Not affiliated with the project, just a happy user) I believe you can modify verifier contract yourself before deploying it.

**Comment by sobolev-igor** [comment]
Yes, I can do it myself, but I've opened an issue cause I thought it may be helpful for others)

**Comment by Schaeff** [comment]
Hi @sobolev-igor and thanks for flagging that! I believe the only `assert` we use are from https://github.com/musalbas/solidity-BN256G2 so that's where you should make your case :)
