### ISSUE TITLE
testing proof with web3js

### ISSUE THREAD

**Issue by ariary** [Zokrates/ZoKrates#42]
I have been playing with ZoKrates  for a few days but I can't achieve a verification process with a true statement. It is alway FALSE I tried to follow the tutorial of the readme but I encountered some difficulties: **the verification always returns "false"**. I mean, of course, I should use the toolbox with a wrong way

This is the basic code I want to test:
```
def main(x,private s1,private s2):
    s1 + s2 + x == 15
    return 1
```

Then when I generate proof I have this output:

    Generating proof...
    Using Witness: {"~one": 1, "x": 5, "~out_0": 1, "s2": 5, "s1": 5}
    Public inputs: [1, 5, 1]
    Private inputs: [5, 5]
    * Elements of w skipped: 0 (-nan%)
    * Elements of w processed with special addition: 0 (-nan%)
    * Elements of w remaining: 0 (-nan%)
    * Elements of w skipped: 0 (-nan%)
    * Elements of w processed with special addition: 0 (-nan%)
    * Elements of w remaining: 0 (-nan%)
    * Elements of w skipped: 0 (0.00%)
    * Elements of w processed with special addition: 1 (25.00%)
    * Elements of w remaining: 3 (75.00%)
    * Elements of w skipped: 0 (0.00%)
    * Elements of w processed with special addition: 1 (25.00%)
    * Elements of w remaining: 3 (75.00%)
    * G1 elements in proof: 7
    * G2 elements in proof: 1
    * Proof size in bits: 2294
    Proof:
    A = 0x17ae0464d4c0d1937fee027b520ca9ec7ee4f2abf70b52a75c636d6735005392, 0x281134f906ab1cb3011cb6207a1f9ef5398045af52c3eff8e9db9f50c8cf3828
    A_p = 0x1ac693cdd14a1206f930729a929b3b39721f838446061af6311c4ed30c428426, 0x2712e90c78ec9e0e5ccf3356e23855484c4073bb274194635b612b63f4ac8be3
    B = [0x883a4f310a3966a5cb139b59288c78aa8a8a9a8b4bf48792420d5184f8fb8b5, 0x201d60787fd856c24e7b45dab7cb41a79ff348153683dbf82b5d77d14e168ae5], [0x1d9ccf0e5d091b85a795d74abc13625e531cb65115589b999c9c0e05b7310920, 0x21a3beba1014556c091197668c9380cc37e420b4232fa5c35a175ee00bfe92f4]
    B_p = 0x1d0c580e2431894c97e6bee5de2e396477beabebeb4606c21d241328d0ca139d, 0x2add4d48ef20738cf6540cc530bf80948bd6cb8b180cf4a3ec412e0dc58fe3de
    C = 0x20ba1cacf4ebbc3c1c29d11946b1c38151cb44d0803d628fa69e1ae8e930e7c7, 0x1dc6686abe23aa65b1653fab516386b86d7deae2ac817cf7fb3d89ad4d1da8ca
    C_p = 0xb292b7ab8b91c84eb61338fa9837465d94e3e82c1e029c55b4d754161242b13, 0x15f60d3a7192a31f6da6804e960cbd13198a710f14c4860fd5ea1453eb2cf131
    H = 0x2621bd887a4e502ae5d9660a56702be8a7567bee0507d8af711be5fca888ff88, 0x2e905b72b811929ea2475d8c0df0a5815e329aebe787a37cf62a60ba4dad0c5c
    K = 0xf1bd7f2d6fe7efcb5480bd8743c359153dc73153039f0c76c90b62431ca1ac2, 0x151b78bf375d6d20a2f242e70db41d25183a594632e553f97d27570d15551ff
    generate-proof successful: true

(I used as value for x = 5, s1 = 5, s2 = 5 )

Here I am confused, the length of public inputs is 3 but in my verifier.sol generated the array expected in `verifyTx` is  of length 2 ... 

Then, I  deploy verifier.sol & SumsToFifteen.sol (please find them attached), and I try to test the result of my proof with the web3js script verifier.js (but it is always false):
```
proof: 0
success: false
```

**Please, could you help me to find a way to make all this stuff working?**

Thank's in advance

-----
***Note:***

 - in verifier.js I try all kind of mix for `I` (`I=[1, 5 ,1]`, `I=[1,
   5]`, `I=[5,1]`, ...) 
   

    eth.contract(abi).at("0xfc1684a8af3e6bf532482c356e5b2cef9cad144f")

   referenced obviously to the contract address of the `SumsToFifteen.sol`
 - I've also tried to change the length of the input both files `SumToFifteen.sol` and `verify.sol` to 2 without any success

 
---

[verifier.js](https://github.com/JacobEberhardt/ZoKrates/files/1876267/verifier_js.txt)
[verifier.sol](https://github.com/JacobEberhardt/ZoKrates/files/1876269/verifier_sol.txt)
[SumsToFifteen.sol](https://github.com/JacobEberhardt/ZoKrates/files/1876275/SumsToFifteen.txt)

**Comment by lovesh** [comment]
@ariary  I tried to run the provided scripts and i get `Error: invalid address` at `VerifierContract.verifyFifteen(...`. I am getting similar invalid address errors when i have tried to run the other generated contracts and they occur when the `VerifyTx` is called. Can you share what your `solc` and truffle versions are?
From the code i have seen, the likely place that it can occur is the inline assembly where `call` is used since the second argument to `call` are numbers like `6`, `7` and `8` but from the documentation they should be addresses of other contracts

**Comment by Schaeff** [comment]
What you call `I` should be your public input variables then your output variables. Here `[5,1]`.
I think adding quotes to the arguments will help. Agree this should be clearer!
My test:
```
verifier.verifyTx.call([0xaaa16294a5081f3e60f5db36a78b697c83f8d55fc2714ab37c8a5d5059dd618, 0x16e7c94de56ae92a6fd55b193171fb67ae16fc0598ce992d41ae3e17e72bf4d],[0xf07dd9017bf3d7d98396e0c4cd9b1191ebf30f08749fc0569aa879eec76474d, 0xab7d0efe70dc75dd4ec6e3370d4baf71553e6bf7690775526e369975bd5d25b],[[0x111c53d986163a8de48df856f80c5e9c20d87da0de4e5e64b6d4859503151edd, 0x9b590fb204f33c1434bbac4db04b0a85913ebb1aa09f6add2f8f3875e364dec], [0x3912e9f79b64aee4859940ff63d63db28b1d3a5e694c4f737f565a2f7dc4b93, 0x11d77bfb1e0b8d81b2e55bb50c57bcd9b4efb6f66a832acb0e447920f783de42]],[0x29c92d7e5cf7d31aa7f59e3b09cc2e772e847b914aa899875fe976b0b5bef5f8, 0x256d74fe776d9e5ba94941fbad1881f64cc139b4b31a0574a34d241647c3f80a],[0x2752db2e64e682626fa67efa2da5e0170407d4cc5aa33b5e5acdb921737f7536, 0xbfe77e866f92a6b50ccead697bdcbec2f193bc0bfa95c8a316d3087c797d10e],[0x27167eae34903496492d62abaf813ae89cebbfa9d046387d37a99bfd4a39bb10, 0x18f56a5a1b88e737c6bcd4582f387323c73e4800812e9a5c206c470aed5c37de],[0x1b3b2f4e2fa4faedbbd1aa845e56c62e3375c1387fec95d8e71d345e119499b9, 0x2e939d0b1e3be5ff148e6fe5fea6a6f8b7e3132ef45cfbaca1539cc920ac936d],[0x248e145431576c740d0da9e21b3b0cf1c7f85862d2cbd011f4903d382ef2aec5, 0xdee10706a63307a52b914ec429cf44004ff9c9ee01c022567985ab032844a9],[15,1],
 function(e, r) {console.log(r)})

false

verifier.verifyTx.call(["0xaaa16294a5081f3e60f5db36a78b697c83f8d55fc2714ab37c8a5d5059dd618", "0x16e7c94de56ae92a6fd55b193171fb67ae16fc0598ce992d41ae3e17e72bf4d"],["0xf07dd9017bf3d7d98396e0c4cd9b1191ebf30f08749fc0569aa879eec76474d", "0xab7d0efe70dc75dd4ec6e3370d4baf71553e6bf7690775526e369975bd5d25b"],[["0x111c53d986163a8de48df856f80c5e9c20d87da0de4e5e64b6d4859503151edd", "0x9b590fb204f33c1434bbac4db04b0a85913ebb1aa09f6add2f8f3875e364dec"], ["0x3912e9f79b64aee4859940ff63d63db28b1d3a5e694c4f737f565a2f7dc4b93", "0x11d77bfb1e0b8d81b2e55bb50c57bcd9b4efb6f66a832acb0e447920f783de42"]],["0x29c92d7e5cf7d31aa7f59e3b09cc2e772e847b914aa899875fe976b0b5bef5f8", "0x256d74fe776d9e5ba94941fbad1881f64cc139b4b31a0574a34d241647c3f80a"],["0x2752db2e64e682626fa67efa2da5e0170407d4cc5aa33b5e5acdb921737f7536", "0xbfe77e866f92a6b50ccead697bdcbec2f193bc0bfa95c8a316d3087c797d10e"],["0x27167eae34903496492d62abaf813ae89cebbfa9d046387d37a99bfd4a39bb10", "0x18f56a5a1b88e737c6bcd4582f387323c73e4800812e9a5c206c470aed5c37de"],["0x1b3b2f4e2fa4faedbbd1aa845e56c62e3375c1387fec95d8e71d345e119499b9", "0x2e939d0b1e3be5ff148e6fe5fea6a6f8b7e3132ef45cfbaca1539cc920ac936d"],["0x248e145431576c740d0da9e21b3b0cf1c7f85862d2cbd011f4903d382ef2aec5", "0xdee10706a63307a52b914ec429cf44004ff9c9ee01c022567985ab032844a9"],
[15,1],
 function(e, r) {console.log(r)})

true
```

Let me know if it helps!

**Comment by lovesh** [comment]
I was not providing the `from` address in the contract call, hence the invalid address. Once i resolved that, i get `Error: VM Exception while processing transaction: invalid opcode`. Now i dont know at what point the invalid opcode occurs, i know the program counter but don't know how i would use it. The quotes have no impact

**Comment by ariary** [comment]
@lovesh when I use truffle I have the same issue (and debugging seems quite difficult). In fact, I succeeded with the factorization code provided in the example directory. I will try again with a personnal ` .code`

**Comment by lovesh** [comment]
@ariary I was trying to run the `SumsToFifteen.sol` given by you for now. And i did add the `[`.

**Comment by doniamansouri** [comment]
@ariary  I followed the tutorial but still having the same issue. false for both inputs. I need help please

**Comment by doniamansouri** [comment]
@lovesh same as you, but nothing has changed.

**Comment by ariary** [comment]
@doniamansouri if you want to use this example:
```
def main(x, private s1, private s2):
   x  ==  s1 + s2 
    return 1

```
 (I will explain for a test with Truffle please find some documentation on it [here](http://truffleframework.com/tutorials/debugging-a-smart-contract)) 
Save it in a file `sums.code` then compile it: `./zokrates compile -i path/to/sums.code`
then: `./zokrates setup`
and: `./zokrates compute-witness -a 15 --interactive `(this will ask you in command line prompt 2 that numbers the sum is 15)
and finally `./zokrates generate-proof` (note the result A,B,etc..)
**_Caution:_** the result of this command line would indicate public input [1,15,1] but later you provide [15,1] as public input to the smart contract which corresponds to your public input variables then your output variables.
And: `./zokrates export-verifier` to create the `verifier.sol` contract

Deploy the contract with truffle and then enter your proof in the command line(A,...), mine is:
```
A = ["0x1195b821d5ad91bd6d55ff91e3d0efc8ac0228c7c64dfa15ae7b4125bd67f191", "0x88bac4c41191731af8bbdea82f5b42300e0150562c6bdcd4a874dc9cf0fe9b9"]
A_p = ["0x566979a1c34b3905ee7f22f1523a4a9f810af557bd9187940e02f9a7026fcfe", "0x2a4197068e1e8b6cb521f12bdde9bc388e22af98363aa7fefba22d5a8031625d"]
B = [["0x10eae764afefc6cd52734d149c00c0852eb2cce96fbd4e6ef55ebda08010cc6f", "0x1cdd7c8750703aa9d5c108951bab4d179aa54c17ec4e7c989d4407fbab82624b"], ["0x25cffa696941618310378e6c9b4f4a68f078f93b42efcb081018d376e302af08", "0x1c1d23816a6a425f42460fe6b23a685ba39a9d3c8ff1cd37d391ce7730a85a2"]]
B_p = ["0xc434e4a78c43d92045bebbaad02ebe50d8383232fe40d95705047424c7baf43", "0x275c0666f531164251eaeedef8e49fa7a0523c4d5f9178b381c46823c340fde5"]
C = ["0x4fa3311ed09091bd6160c9197a4681731a60b06f7eb16028ea00cffe64b03c3", "0x10c0bfe297621d51322be8380605d25c6c2137ab6621e32c27410bd35ee19335"]
C_p = ["0xd5fece59820a8014f8d2352b493d91197f4f288c4d081209f2e9d45c0c771d1", "0x11575c85157e3a44999b013e21092b47037b914623e7e5a876d64843175c9f43"]
H = ["0xcc3873347d5139f4eec734ba0ecea637864f42891b182c97b5cb32fed7be9cb", "0x1c6b6e98cfed7e21f73d0c6a9de1cbebaa4cd4cf89a84456f8ef71cb179409b5"]
K = ["0x1a3e9f5fe4cc7af1f74cf78f8249cd430e9ce05817e0332eed8a891bad3169c6", "0x2c6a58c2b49f3708b92f4e0cdd8e6302d203af8d73208ecc65b13fd139cfb485"]
```
and the public input `I`, mine is:
`I=[15,1]`

Finally test your proof with this line:
`verifier.deployed().then(function(instance){return instance.verifyTx.call(A,A_p,B,B_p,C,C_p,H,K,I);}).then(function(value){return value});`

**Comment by doniamansouri** [comment]
thanks a lot @ariary it works. but I didn't understand why it doesn't work with a private blockchain. it might be related to the method call? I tried it with call and with send transaction, but it always returns false. In the tutorial, it is mentioned to use call instead of send transaction, "I do not know why it is required to transact instead of call but that is the way it is."

**Comment by doniamansouri** [comment]
The program is written in higher level language? is it? if yes so have you any documentation about it  please.

**Comment by Schaeff** [comment]
@doniamansouri You can absolutely use Zokrates in any Ethereum based blockchain, assuming the chain you're using implements the Byzantium precompiles, ie clients are compatible and your genesis block includes them, for example for Parity https://github.com/paritytech/parity/blob/60f112228faa17d63531273192280fe08cadfb47/ethcore/res/authority_round.json , you're looking at addresses 0x5 through 0x8.

It is indeed a DSL which is still experimental for now so check the examples folder and do ask questions on Gitter!

**Comment by doniamansouri** [comment]
any help about how to hide sensitive data in a smart contract using Zokrates

**Comment by doniamansouri** [comment]
@Schaeff  didn't really understand what you meant
