### ISSUE TITLE
Remove overly-specialized testing condition in integration test

### ISSUE THREAD

**Issue by JacobEberhardt** [Zokrates/ZoKrates#420]
https://github.com/Zokrates/ZoKrates/blob/87312a55e94055f14f95afeaa2790783d79a1ee5/zokrates_cli/tests/integration.rs#L80-L84

Sha is available with both, bellman and libsnark backends. Hence, this check for a specific backend should be removed.

**Comment by Schaeff** [comment]
Fixed in #422
