### ISSUE TITLE
Add comparison of arrays in boolean expressions

### ISSUE THREAD

**Issue by paulperegud** [Zokrates/ZoKrates#421]
Example.

Proving that circuit was fed with left-most element in merkle tree requires checking that for every position where selector takes value of 0, the corresponding part of the merkle path describes an empty subtree. Comparisons in boolean expressions don't allow to compare arrays, making it hard.

**Comment by paulperegud** [comment]
In the mean time this can be used as a workaround.

```
def arr_eq(field[256] a, field[256] b) -> (field):
    field equal = 1
    for field i in 0..256 do
        equal = if (equal == 1) && (a[i] == b[i]) then 1 else 0 fi
    endfor
    return equal
```

**Comment by Schaeff** [comment]
I think that makes sense! To clarify, array equality in *assertions* is already available, but not in boolean expressions. 

By the way, I think that it's more efficient with

```
def arr_eq(field[256] a, field[256] b) -> (field):
    field res = 0
    for field i in 0..256 do
        res = res + if a[i] == b[i] then 1 else 0 fi
    endfor
    return if res == 256 then 1 else 0 fi
```
