### ISSUE TITLE
How to generate a proof from contract: Question

### ISSUE THREAD

**Issue by bindernet** [Zokrates/ZoKrates#432]
Hi, new to the field, just managed to get everything working end to end - thanks :-)
I can see that the compute-witness method uses the generated out file. If the prover doesn't have access to this file, is there a way that it can be retrieved from the blockchain, using truffle or whatever? 

The documentation for an end to end process is somewhat lacking (understandably as deployment etc. is a different toolset).

**Comment by Schaeff** [comment]
Hi @bindernet and welcome!
It is up to you if you want to make the program available on the blockchain. It can get quite large so you should make it is what you want.
At this point, we do not specify how the program is distributed as it depends on the use-case: you could bundle it with a prover in a wallet, serve it in a web page, etc..
If you have a specific use case in mind, do share!

**Comment by bindernet** [comment]
Thanks a lot. 
I'm investigating letting an institution share that they know something about an individual (with a verifier contract)
If the prover wanted to confirm that they also know the same thing they would prove against the contract, providing personal details as private inputs.

I'm not 100% sure this a good fit, or whether just publishing hashes of the individual's details might be an alternative solution. (prover calculates a hash based on the details and sees if it exists at the first institution)

I have a further question - do Zokrates contracts emit events by default? I'm currently working out how to view them...

**Comment by Schaeff** [comment]
Yes we do emit events at the moment, you can change that too if that doesn't fit your use case. I'm going to close this but feel free to reach out on gitter.
