### ISSUE TITLE
About Vulnerability allowing double spend in Verifier.sol

### ISSUE THREAD

**Issue by BlockHeader** [Zokrates/ZoKrates#441]
https://github.com/kobigurk/semaphore/issues/16

It's better to add the check and ensure public inputs are less than the scalar field size.

**Comment by LusWar** [comment]
I read a Chinese article introducing this vulnerability (https://zhuanlan.zhihu.com/p/75632029), which mentioned that Zokrates has fixed this vulnerability. I checked the code submission record of Zokrates and found no information to fix the vulnerability. I want to know if Zokrates has fixed this vulnerability.

**Comment by BlockHeader** [comment]
I checked the latest source code. The issue is NOT fixed: 
You can locate the verify function in zokrates_core/src/proof_system/bn128/g16.rs。

**Comment by LusWar** [comment]
> I checked the latest source code. The issue is NOT fixed:
> You can locate the verify function in zokrates_core/src/proof_system/bn128/g16.rs。

thx

**Comment by Schaeff** [comment]
Fix now deployed, closing.

**Comment by lucasvo** [comment]
@Schaeff how was this fixed? Did the generated verifier.sol change?

**Comment by JacobEberhardt** [comment]
The verifier.sol, which is generated by ZoKrates, now includes a range check.
