### ISSUE TITLE
Unexpected number comparison result

### ISSUE THREAD

**Issue by magrady24** [Zokrates/ZoKrates#451]
I got some unexpected number comparison results. I suspect that the implementation of the comparison (such as Lt) in the R1CS conversion step (by the flatten) may be wrong in the case of larger operands.

I wonder why it is necessary to multiply the result of the final subtraction by 2? This will cause the "security" protection that lhs and rhs must less than 2^252 (=pow(2,252)) to fail. When b > a && q - 2^253 < 2*(b-a) = q - 2*(a-b) < 2^253 under E(F_p) with order q (i.e. oprands modulo q), then q - 2^253 < 2*(a-b) < 2^253, so the bit-253 (as value 2^253) of 2*(a-b) is unset, but in fact (a-b) shall be considered negative rather than positive or zero. In other words, I think the negative constraint, which only checks the bit-253 of 2*(a-b) , is a insufficient condition, and which may result in illegal values passing the range constraint even when 0 <= a, b < 2^252 is confirmed by bits-extracting constraints.
(The order q for default BN curve: 21888242871839275222246405745257275088548364400416034343698204186575808495617, approx = 1.512 * 2^253)

https://github.com/Zokrates/ZoKrates/blob/bb98ab1c0426ceeaa2d181fbfbfdc616b8365c6b/zokrates_core/src/flatten/mod.rs#L237

Is it a mistake here or am I getting something wrong? I saw #99 and #205 but these seems to be the case when operand >= 2^252. If my thoughts are wrong, please correct me.

Some tests here

The program:
```
def main(field a,field b) -> (field):
    return if a < b then 1 else 0 fi
```

Run in bash:
```
zokrates compute-witness -a 0 0 | tail -n1 # 0, fine
zokrates compute-witness -a 0 1 | tail -n1 # 1, fine
zokrates compute-witness -a 1 0 | tail -n1 # 0, fine
zokrates compute-witness -a 0 3618502788666131106986593281521497120414687020801267626233049500247285301248 | tail -n1 # 1, seems ok
zokrates compute-witness -a 0 3707115858587375397150016309585643303444808158605481919383003092793333645312 | tail -n1 # 1, still ok...
zokrates compute-witness -a 0 3707115858587375397150016309585643303444808158605481919383003092793333645313 | tail -n1 # 0, wrong?
zokrates compute-witness -a 0 7237005577332262213973186563042994240829374041602535252466099000494570602495 | tail -n1 # 0, wrong?
zokrates compute-witness -a 0 7237005577332262213973186563042994240829374041602535252466099000494570602496 | tail -n1 # 2**252, fail as expected (impossible constraints)
```

**Comment by JacobEberhardt** [comment]
Thank you for reporting!
Fixed in #464
