### ISSUE TITLE
File extensions are confusing

### ISSUE THREAD

**Issue by fulldecent** [Zokrates/ZoKrates#456]
Currently the input for the compile action is accepting .pcode and .code files. But the output default is `out.code`.

This could be confusing because that `.code` file is a different meaning.

Recommending that the output be of type `.zir`, i.e. ZoKrates Internal Representation.

**Comment by fulldecent** [comment]
I'm not sure how to make the file names more clear, but this is a confused question, closing

**Comment by fulldecent** [comment]
Since the input and output files are both `.code` file and the have different formats this can lead to confusion.

Recommending to adopt this proposed default file naming scheme for documentation examples and implicit defaults if file names are not given to the CLI.

 - source.code The input source code, ready to compile
 - compiled.zcode The compiled code, human readible (ZoKrates normally calls this out.code)
 - compiled.zir The compiled code, ZoKrates binary format (ZoKrates normally calls this out)
 - proving.key The key to generate proofs, binary format
 - verification.key The key to verify proofs, binary format
 - verifier.sol Example of a verifier Solidity contract (not compliant with ERC-1922)
 - variables.inf A list of the variables used in the R1CS (not sure if this file is still used)

**Comment by Schaeff** [comment]
Good points. Our plan for this is [here](https://github.com/Zokrates/ZoKrates/issues/392#issuecomment-508048932)

Correct, `variables.inf` isn't used anymore, this needs to be removed.

**Comment by fulldecent** [comment]
Thank you for the reference. Notes added there. PR added for something related. But closing this issue.
