### ISSUE TITLE
Can't get started using ZoKrates, installation fails

### ISSUE THREAD

**Issue by johannesmols** [Zokrates/ZoKrates#469]
Hello everyone, sorry if this is an stupid question but I can't seem to find anything about my issue.
I'm trying to implement zkSNARKs into my Ethereum project and found this neat project.
However, I can't seem to properly install it.

I'm on Windows and have installed the Docker Desktop application from their homepage.
I found [this](https://github.com/jstoxrocky/zksnarks_example) and tried to run the commands to get started:

```
git clone https://github.com/JacobEberhardt/ZoKrates.git
cd ZoKrates
docker build -t zokrates .
```

When I run `docker build -t zokrates .`, it starts running and then gives me the following error message: 
```
Step 9/14 : RUN /tmp/install_libsnark_prerequisites.sh
 ---> Running in 07edb8499659
/bin/sh: 1: /tmp/install_libsnark_prerequisites.sh: not found
The command '/bin/sh -c /tmp/install_libsnark_prerequisites.sh' returned a non-zero code: 127
```

I couldn't find anything about this anywhere and hope that somebody can explain what is going on here.

**Comment by johannesmols** [comment]
It turns out that 0.4.11 is just broken for me.
After scratching my head about this all day, I just tried with 0.4.10 and that works perfectly.

**Comment by JacobEberhardt** [comment]
Thanks for the feedback, nice that you got it to work! 
Will close this.

**Comment by Fattah-Saqib** [comment]
I am having the exact same issue in all the versions. What might be the issue?
