### ISSUE TITLE
Zokrates not supported on CentOS

### ISSUE THREAD

**Issue by Asad97akay** [Zokrates/ZoKrates#470]
Hi guys im having a really weird error while developing on zokrates
So the error I get is: 5563 Illegal instruction (core dumped) ./zokrates setup -i out_preimage --proving-scheme gm17
I also found out that when you switch to standard proving scheme (g16) everything is working fine.

I further found that it is working under Windows and Debian
Our OS is CentOS7

can anybody please help me with the issue? or does anybody know that if zokrates has support for centOS?

**Comment by Schaeff** [comment]
Hi thanks for filing this. GM17 is based on cpp bindings which are definitely one of the weak points of the codebase when looking at cross platform. We're aiming at getting rid of cpp so I opened #473 which would most likely fix this. In the meantime, I suggest you use Groth16, or a different OS.
