### ISSUE TITLE
Add 2-dimensional arrays

### ISSUE THREAD

**Issue by iAmMichaelConnor** [Zokrates/ZoKrates#477]
Hi!

I'm not sure if this has been considered before, and I'm sure it's an extremely fiddly feature to implement, but thought I'd raise an issue with an explanation of why it would be useful, and possible syntax:

Currently we have syntax for a 1-dimensional array:

`field[n] myArray =  [0; n] // initialises an array of n 0's`

Since I find myself working with bits quite often, I quite often find myself wishing for 2-d array syntax so I can unpack the elements of myArray into bits (in order to do sha256 hashing on them, for example).
Instead what I'm currently having to do, is pass `myArray` into `main()` as n parameters :
`main(field myArray1, field myArray2, ..., field myArrayn)`.
Then I can convert to bits:
`field[128] myArray1Bits = unpack128(myArray1)`
`field[128] myArray2Bits = unpack128(myArray2)`
...
`field[128] myArraynBits = unpack128(myArrayn)`

This requires n lines of code and becomes very prone to mistakes.

Instead, it would be beneficial to have 2-dimensional arrays to support syntax such as:
```
main(field[n] myArray)->(field):
field[n][m] myArrayBits // declaration of an n x m array (lazy syntax: this might need to be initialised with values)
field leaf = 1 // initialise some leaf of a tree (for example)
field hash = leaf // lazy commencement of iteration
for field i in 0..n do
     myArrayBits[i] = unpack128(myArray[i])
     hash = sha256(hash, myArrayBits[i])
endfor
field root = hash
```
This isn't necessarily a practical example, but hopefully illustrates the usefulness of 2-d arrays to create more readable and error-free code - especially when working with bits.

Possible syntax features:
`field[n][m] myBigMatrix // declaration of an n x m array`
`field[3][2] myMatrix = [a, b; c, d; e, f] // Matlab-like syntax for declaring 2-d arrays`
`myMatrix[1][2] = 4 // sets b to 4`
`myMatrix[2] = [8, 9] // sets c to 8 and d to 9`
`myMatrix[1] = [...myMatrix[2]] // copies values from 'row 2' to 'row 1'`
`myMatrix[3] = myBigMatrix[3][4..5] // copies elements [3][4] and [3][5] to myMatrix[3][1] and myMatrix[3][2] respectively.`

**Comment by JacobEberhardt** [comment]
Hey Michael, thank you a lot for your input - really appreciated!

Did you see the #434 we recently merged? It implemented multi-dimensional arrays of any type and is available on develop.

**Comment by iAmMichaelConnor** [comment]
@JacobEberhardt no way? That's game changing! Thanks for the prompt feedback and congrats for implementing it! The syntax chosen looks nice and intuitive.

I'll close this issue.
