### ISSUE TITLE
Compute witness doesn't throw an error, but also doesn't generate a witness file.

### ISSUE THREAD

**Issue by willKim19** [Zokrates/ZoKrates#479]
I've gotten compute-witness to work with other files, but when it comes to a certain code file, it doesn't work. I suppose it's likely an issue with the code file itself, but I'm not receiving any error or indication of what might be going wrong.

**Comment by JacobEberhardt** [comment]
Hey @willKim19, thanks for your report.
It would be great if you could provide us with your ZoKrates code as well as the inputs you used, so we can reproduce the behavior.
