### ISSUE TITLE
Add equality operator for booelans

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#483]
this works:
`field out = if sizeUnknown  then 1 else 0 fi`

but this one fails:
`field out = if sizeUnknown  == true then 1 else 0 fi`

with the following error:

> Cannot compare sizeUnknown of type bool to true of type bool

**Comment by garvita-jain** [comment]
Hi! I would like to work on this project. Can you guide me about where to start since I am fairly new to Rust.
Thanks :)

**Comment by Schaeff** [comment]
Hey @garvita-jain, @petscheit is already on this issue but do contact us on Gitter so we can find something you'd be interested to help with!  🎉

**Comment by Schaeff** [comment]
Addressed in #492
