### ISSUE TITLE
Add 'environment variables'

### ISSUE THREAD

**Issue by iAmMichaelConnor** [Zokrates/ZoKrates#488]
A common use-case might be a Merkle inclusion proof.

Now, in production, a developer might want the Merkle Tree to be 64 deep (for example). But such a large tree would take a long time to generate proofs when the developer is testing their code.

Instead, a developer might want to test on a much smaller tree, to quickly test changes. Environment variables which get fixed _before_ the trusted setup would be helpful. 

Example: `env tree_depth = 4` could be set at the top of the `.code` file.
Then within the `main()` function, we could refer to `tree_depth` in a fixed way:
`for i = 0 .. tree_depth`

Then, when I'm done testing, I can update the environment variable in one place, and push my code.

Another example: `env array_size = 128` could be set at the top of the `.code` file.
Then within the `main()` function, we could refer to `array_size` in a fixed way:
`main(field[array_size] myArray)`

The idea's come from experience of having a bug in my .code file and it taking ages to find because of the slow setup and proof generation times for a 32-deep tree.

**Comment by Schaeff** [comment]
This is covered by constants and constant generics
