### ISSUE TITLE
Include full signature in JSON-ABI

### ISSUE THREAD

**Issue by JacobEberhardt** [Zokrates/ZoKrates#491]
In the current version of the json-abi, we only encode type information in json-objects.
We expect these objects to be structured correctly when provided as inputs and do not export an explicit ABI description, yet.
For consuming applications, it would be beneficial to have the full signature available, i.e., variable names, modifiers, and their structure.
Furthermore, this would remove the need to provide the parameters in order.

If we decided to provide a separate ABI description, it could look like this:
For a simple main function `def main (private field a, public bool b)`
```
{ //enclosing object
    "a": {
          "mod": "private",
          "type": "field",
          },
    "b": {
         "mod: public",
         "type": bool"
}
```
A valid input to that ABI would be
```
{
 "a": "23",
 "b": false,
}
```

**Comment by edisinovcic** [comment]
Hackmd reference doc:
https://hackmd.io/@0Y_-khwIRDCGImsY0ILMqQ/zokrates-abi/edit

**Comment by JacobEberhardt** [comment]
Updated with my proposal

**Comment by Schaeff** [comment]
Implemented, closing
