### ISSUE TITLE
Research syntax highlighting

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#503]
Let's put together a survey of options for syntax highlighting

ZoKrates parser: https://github.com/Zokrates/ZoKrates/tree/master/zokrates_parser

Solidity example: https://github.com/raphaelhuefner/ace-mode-solidity
Support for vscode: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by edisinovcic** [comment]
Testing it in here: Implement in: https://ace.c9.io/tool/mode_creator.html
