### ISSUE TITLE
why sha256packed([0, 0, 0, 5]) not equal to sha256(5) which is ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d ?

### ISSUE THREAD

**Issue by dreamisadream** [Zokrates/ZoKrates#507]

**Comment by JacobEberhardt** [comment]
Could you please provide a code sample, so we know exactly what you are trying to do?
Most likely your issue is that the simple sha function is only the compression function and does not apply padding. Always use packed or padded versions for compliance with other sha implementations.

**Comment by dreamisadream** [comment]
Thanks for your reply.
I'am learning Zokrates from https://zokrates.github.io/sha256example.html,
but I have no idea why sha256packed([0, 0, 0, 5])
returns 0xc6481e22c5ff4164af680b8cfaa5e8ed3120eeff89c4f307c4a6faaae059ce10.
Is there a simple function that I can input a number and gets its sha value
without packed or padding?

Thanks a lot.


JacobEberhardt <notifications@github.com> 於 2019年11月6日 週三 下午7:50寫道：

**Comment by JacobEberhardt** [comment]
The result is the correct hash value. You can use an online tool to calculate the sha of the input value.
The input, after applying padding in hex would be:
`00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005`.
You can use sha256 and hex input to calculate the hash [here](https://www.liavaag.org/English/SHA-Generator/) for example.
This gives you exactly the result you obtain from ZoKrates.
Maybe it's also worth to check out this test case:
https://github.com/Zokrates/ZoKrates/blob/master/zokrates_stdlib/tests/tests/hashes/sha256/512bitPadded.zok

**Comment by dreamisadream** [comment]
Wow, how nice of you !
Thanks Zokrates team.

JacobEberhardt <notifications@github.com> 於 2019年11月6日 週三 下午9:20寫道：
