### ISSUE TITLE
compute witness with array as input

### ISSUE THREAD

**Issue by benjaminstrasser** [Zokrates/ZoKrates#508]
Is it currently possible to give inputs to compute witness in array format (1-dimensional and 2-dimensional) .

I have somthing like 
 ```
def main(field[256] value) -> (field):
    return 1
```

when i call 
```
zokrates compute-witness -a [0,1,1,1,1,1,1,1,0,1,0,1,0,1,1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,1,1,0,0,1,1,1,0,0,0,0,1,1,0,0,1,0,0,1,1,1,0,0,1,1,1,0,0,1,0,0,1,1,0,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,1,1,1,0,1,1,0,1,1,0,0,0,1,1,0,1,0,0,0,0,1,1,1,1,0,0,1,0,1,0,1,1,0,0,0,0,1,1,0,1,1,0,1,1,1,0,0,0,1,1,0,0,1,1,1,1,1,0,1,1,0,1,1,0,1,1,1,1,1,0,0,1,0,0,1,0,0,1,1,0,1,0,1,0,0,1,1,1,1,1,0,0,1,1,0,1,1,0,0,0,1,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,1,0,1,1,1,0,0,1,0,1,0,1,1,0,1,1]
```

 i get the following error
```
Could not parse argument: [0,1,1,1,1,1,1,1,0,1,0,1,0,1,1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,1,1,0,0,1,1,1,0,0,0,0,1,1,0,0,1,0,0,1,1,1,0,0,1,1,1,0,0,1,0,0,1,1,0,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,1,1,1,0,1,1,0,1,1,0,0,0,1,1,0,1,0,0,0,0,1,1,1,1,0,0,1,0,1,0,1,1,0,0,0,0,1,1,0,1,1,0,1,1,1,0,0,0,1,1,0,0,1,1,1,1,1,0,1,1,0,1,1,0,1,1,1,1,1,0,0,1,0,0,1,0,0,1,1,0,1,0,1,0,0,1,1,1,1,1,0,0,1,1,0,1,1,0,0,0,1,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,1,0,1,1,1,0,0,1,0,1,0,1,1,0,1,1]
```

or f.e for 2-dimensional arrays
```
zokrates compute-witness -a [[1,2,3],[4,5,6]]
```

**Comment by JacobEberhardt** [comment]
Hey Benjamin, you have two options, here.
Either you provide the values as space separated list as in [this example](https://zokrates.github.io/sha256example.html) in the arguments, or you use our JSON-ABI to have a representation closer to the actual data structure.
The JSON-ABI is currently still subject to changes and hence not part of the documentation. However, you can find a usage example in our test cases, e.g., [these inputs](https://github.com/Zokrates/ZoKrates/blob/master/zokrates_cli/tests/code/multidim_update.arguments.json)
for 
[this program](https://github.com/Zokrates/ZoKrates/blob/master/zokrates_cli/tests/code/multidim_update.zok)
If you want to use this ABI, make sure to set the `--abi` and `--stdin` flags for witness generation and provide the json file through stdin, potentially using pipes (`|`).

**Comment by benjaminstrasser** [comment]
@JacobEberhardt 
Thank you for the fast response
