### ISSUE TITLE
Adding a native verifier in ZoKrates

### ISSUE THREAD

**Issue by nono2357** [Zokrates/ZoKrates#513]
It would be great to be able to verify a proof within ZoKrates, without needing a blockchain environment nor smart contract deployment, and with native Rust speed.

**Comment by benjaminstrasser** [comment]
I am currently thinking about implementing such a solution as we currently need a way to verify proofs on and off chain. I would just need some help grasping the general architecture as the project doesn't seem to have much documentation or I am unable to locate it.

**Comment by Schaeff** [comment]
Correct @benjaminstrasser. 
I am not completely sure what the approach should be: either wrap libsnark's and bellman's verification (as we do for proving), nice as we don't have to write verification logic but verification would still be backend-dependent, or as you suggest write verification logic in Rust (probably using bellman tools, starting with the example of groth 16)

@yelhousni I think you started work on this, could you report here?

**Comment by yelhousni** [comment]
Yes, we did wrap libsnark's verification here (https://github.com/EYBlockchain/zk-swap-ZoKrates/tree/ey/work) for a project.

**Comment by benjaminstrasser** [comment]
@Schaeff 
I would propose, please correct me if I my understanding is incorrect, to implement g16 natively using some tools so libsnark isn't required. For the other schemes as they already require libsnark wrapping it seems to be the sensible way. There we could use some to all of @yelhousni's work.

**Comment by Schaeff** [comment]
Sounds sensible to me @benjaminstrasser, happy to assist if you need anything!
