### ISSUE TITLE
invalid opcode when deployed on ganache-cli

### ISSUE THREAD

**Issue by marinthiercelin** [Zokrates/ZoKrates#519]
Hello,

I have an `invalid opcode` when calling the `verifyTx` method of a verifier contract generated by zokrates. 
My use case is quite complicated, so I repeated the operation with a simple program to isolate the problem:

- I define the following zokrates file `test.zok`:

```
def main(private field secret, field input) -> (field):
    return secret+input
```

- Then I run `zokrates compile -i test.zok`, `zokrates setup`, `zokrates export-verifier`.

- In a terminal I run  `ganache-cli`.

- I then launch Remix IDE, set up the environment to connect to the running `ganache-cli` with the Web4 Provide, import the `verifier.sol`, compile it and deploy it.

- I run `zokrates compute-witness -a 1 2`, and `zokrates generate-proof`.

- In remix, I call the `verifyTx` method of the previously deployed verifier, with the values from `proof.json` as inputs.

I get the following : `transact to Verifier.verifyTx errored: VM Exception while processing transaction: invalid opcode` 

When I use Remix with the `Javascript VM` environment, instead, the error doesn't show up.

Some versions for reproducibility:
- ZoKrates 0.5.0
- Ganache CLI v6.7.0 (ganache-core: 2.8.0)
- Remix compiler 0.5.11+commit.c082d0b4

**Comment by marinthiercelin** [comment]
I have tested it with ganache-cli 6.6.0, 6.5.0, 6.4.0, 6.3.0, 6.1.0 and get the same error.

**Comment by Schaeff** [comment]
> When I use Remix with the Javascript VM environment, instead, the error doesn't show up.

Are you saying the verification works fine? This would suggest this is not an issue with ZoKrates, have you tried asking the ganache people?

**Comment by petscheit** [comment]
Maybe it could be related to [this](https://github.com/trufflesuite/ganache-cli/issues/650)? I was running into a similar issue with the ganache-cli docker image, while it was running fine with Javascript VM

**Comment by marinthiercelin** [comment]
> > When I use Remix with the Javascript VM environment, instead, the error doesn't show up.
> 
> Are you saying the verification works fine? This would suggest this is not an issue with ZoKrates, have you tried asking the ganache people?

Hello sorry, so yes it seems like its a problem specific to ganache. The error doesn't show up when I use the Javascript VM or a geth private test network. I didn't get the time to investigate what in ganache made it fail.
