### ISSUE TITLE
Add variable 'For loop bounds' on nested For loops

### ISSUE THREAD

**Issue by iAmMichaelConnor** [Zokrates/ZoKrates#520]
Hi team! I was just exploring doing 'triangular' for loops, in order to ensure a list contains only unique values:

What I'd like to do is the following 'triangular' nested for loop. Notice how the second loop has lower bound `i`:

```
// check for duplicates
def main(field[256] values) -> ():
    field acc = 1
    for field i in 0..256 do
        for field j in i..256 do
            acc = acc * (values[j] - values[i])
            isNotZero(acc) == 1
        endfor
    endfor

    return
```

This (understandably) fails, because `i` is variable: `thread 'main' panicked at 'not yet implemented: For loop bounds should be constants, found i', zokrates_core/src/absy/from_ast.rs:288:18`

However, in the above code, it's clear that the nested loop's bounds aren't dynamic, because `i` isn't changed within the loop. Therefore, this ought to be allowable.

Are there plans to allow such syntax in future?

**Comment by Schaeff** [comment]
Interesting example! I think the static analyser should be able to handle this case, I'll look into it.

**Comment by Schaeff** [comment]
Update on this for myself and anyone interested: 
This currently clashes with the order in which we process code: we currently have a step which unrolls loops and converts to SSA, and then a constant propagation step. The clash is that to unroll a loop, the bounds need to be known, which requires constant propagation.

A potential solution to that is to run (unroll, propagate) many times until we find a fixed point, modifying the current unroll to only unroll loops with known bounds. The fixed point should be the absence of loops. @leonardoalt I'm curious whether you would have thoughts on this?

**Comment by leonardoalt** [comment]
> A potential solution to that is to run (unroll, propagate) many times until we find a fixed point
This sounds like it'd work as the general solution.
But I think you could also do something specific for nested loops, like "run constant propagation right before you unroll any loop".
The way I imagine this could work is: when you unroll the outer loop in the example, `i` will have a different value for each iteration. When you see the inner loop, propagating will cause `i` to be assigned a constant, so you can unroll the inner loop entirely.
Does that make sense?

**Comment by Schaeff** [comment]
It makes sense, but how does that differ from running constant propagation on the whole program? As instead of `i..256` you could have `(i+x)..256` with `x` a variable declared in a more global scope. Are you saying you unroll until you reach a variable loop, and then backtrack to propagating starting from the beginning of this function's body?

**Comment by iAmMichaelConnor** [comment]
I've stumbled upon a similar example to this issue today, which I thought I'd share here:

Hashing up a Merkle Tree with a fixed number of leaves.

```
                  <-- 1 hash required to get to the root
     /   \
                  <-- 2 hashes required to get to this level
  /  \   /  \
                  <-- 4 hashes required to get to this level
/ \ / \ / \ / \ 
```

The following nested loop, with a variable upper bound would be nice to have:
``` 
  field width = 8 // fixed Merkle Tree width = 2**height, where height = 3

  for field level in 0..3 do
    width = width / 2
    for field i in 0..width // <-- variable upper bound
      // do hashing calculations in here
    endfor
  endfor
```

Notice how, given that `width` was assigned to a static value before the loops, we know that there will be exactly 7 loops overall (4 + 2 + 1).

The reason this notation would be useful, is just to allow more succinct code.
The only way I can think to do this at the moment would be:

``` 
  // first row of hashing:
  for field i in 0..4
    // do hashing calculations in here
  endfor

  // second row of hashing:
  for field i in 0..2
    // do hashing calculations in here
  endfor

  // third row of hashing:
  for field i in 0..1
    // do hashing calculations in here
  endfor
```
... which is a bit less elegant, and less updatable (e.g. if I wanted to have a larger tree in future).

**Comment by Schaeff** [comment]
Great! #550 will enable that usecase
