### ISSUE TITLE
Add support for websnark

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#524]
Add [websnark](https://github.com/iden3/websnark) as a backend when targetting wasm on bn128 g16

**Comment by Schaeff** [comment]
@dark64 would you mind putting your findings here so we can track this?

**Comment by dark64** [comment]
@Schaeff I wrote some concerns [here](https://hackmd.io/f_Dbn7CwSGytvwQJny9CHg?view) regarding this issue.

**Comment by Schaeff** [comment]
Ok I'll close this for now.
