### ISSUE TITLE
SHA-512

### ISSUE THREAD

**Issue by emilbayes** [Zokrates/ZoKrates#528]
Hi!

Looking at the sha256 code in stdlib it uses a special `EMBED` import, which I'm guessing is a compiler intrinsic?

I'm interested in doing sha512hmac in zokrates, since I want to try and make a zkp that if PK1 came from a BIP32 HD seed, then given a chain-code, so does PK2. Maybe this isn't even possible? It was just a quick idea and I went looking for sha512 as the first thing

**Comment by Schaeff** [comment]
Hey Emil, yes at this point we're importing the constraint system for a single sha256 round from bellman. That round is different from the sha512 one so it wouldn't be supported now. We're working on having a native implementation of sha256 so once we have that sha512 would be straight forward.

**Comment by JacobEberhardt** [comment]
In the meantime, our standard library uses a sha256 implementation that is fully written in the ZoKrates language. As described above, extending this to 512 is straight forward.
