### ISSUE TITLE
How to make a circuit that can verify that you know the secret key that matches the public key?

### ISSUE THREAD

**Issue by EunseongBoo** [Zokrates/ZoKrates#529]
Hello I'm a beginner learning zokrates. 

I want to make a circuit that can verify that you know the secret key that matches the public key. The below circuit is implemented using ProofOfOwnership library, but it does not work successfully.  

The ethereum secret key and public key for testing
secret key: 
public key:  

test.zok code
```
import "ecc/proofOfOwnership.zok" as proofOfOwnership
import "ecc/babyjubjubParams.zok" as context

def main(field[2] pk, private field sk) -> (field):
  //prove the public key
  context = context()
  proofOfOwnership(pk, sk, context) == 1
  return 1
```

test.js code
```
const util = require('ethereumjs-util')
const crypto = require('crypto');
const BN = require('bn.js');
const SCALING_FACTOR = new BN('1000000000000000000');

function printZokratesCommand(params) {
  let cmd = 'zokrates compute-witness -a '
  params.forEach(p => {
    cmd += `${new BN(p, 16).toString(10)} `
  })
  console.log(cmd);
}

function getCreateNoteParams(_pubKey, _secKey) {
  let pubKey = new BN(_pubKey, 16).toString(16);
  let secKey = new BN(_secKey, 16).toString(16);
  let privateParams = [pubKey.slice(0,64), pubKey.slice(64), secKey];
  printZokratesCommand(privateParams);
}

getCreateNoteParams(
  '13ec8d3dcdac87a3a528694902294be0770c968bd0bc9a5a7571f9466010240940791f9450a818b6aa71f031eff7aceadc66b53d52b59786a19446e48a9bd57f', // pk
  '0x7abcea3f35fa4229874e55bb29a0da13700de365e2b6e4d41edbb718519089c', // sk
)
```

"Zokrates compute witness -a ~" fails when testing.
![image](https://user-images.githubusercontent.com/20852734/70231008-dee35980-179c-11ea-97be-c248062aaf67.png)

I want to know why the error occurs. The public key and secret key is normal.
I found that "ZoKrates/zokrates_stdlib/tests/tests/ecc/proofOfOwnership.zok" example uses "ecc/babyjubjubParams" as context. and the tested pk&sk is created using "https://github.com/Zokrates/pycrypto".  However, the pyCrypto creates a different public key when using the same secret key.  

How can I solve the problem? What is my fault?

Thanks.

**Comment by fulldecent** [comment]
Please send questions to StackOverflow or similar
