### ISSUE TITLE
verifyTx return false on geth

### ISSUE THREAD

**Issue by beyonderyue** [Zokrates/ZoKrates#534]
Env:
geth:1.8.22
Solidity: 0.5.1

Zokrates: 0.5.1

zok file:
def main(private field a, field b) -> (field):
  field result = if a * a == b then 1 else 0 fi
  return result

I generate a sol file and deploy on the geth.

When I call  verifyTx on Blockchain, it returns false.
But when I use Remix JS VM, verifyTx returns true.
Is there any suggestion on this issue?

**Comment by Schaeff** [comment]
The fact that you're not having issues on the JS VM suggests this is not an issue with ZoKrates. Could you try with a more recent version of geth? This on is almost a year old.

**Comment by beyonderyue** [comment]
I also tried the latest geth 1.9.9, same problem

**Comment by beyonderyue** [comment]
I found the reason... my private geth didn't include Byzantine configuration in the genesis json file.
