### ISSUE TITLE
Compilation error with solc 0.6.1

### ISSUE THREAD

**Issue by marinthiercelin** [Zokrates/ZoKrates#543]
Hello,
I get a strange compilation error when I try to compile the generated `verifier.sol`.
When I compile it with solc, version 0.6.1 I get the following :
```
solc --bin verifier.sol
Error: Expected '(' but got ','
   --> verifier.sol:237:42:
    |
237 |             success := staticcall(sub(gas, 2000), 5, freemem, 0xC0, freemem, 0x20)
    |                                          ^
```
However i don't get the error when I downgrade the solc compiler to the version 0.5.11

**Comment by leekt216** [comment]
It seems like solidity assembly has changed for `gas` on version 0.6
You can fix this with using `gas()` instead. 
I don't know much about Zokrate. But for me, it seems like issue with (BN256G2)[https://github.com/musalbas/solidity-BN256G2] and Pairing library.
I added a PR for updating solidity template

**Comment by marinthiercelin** [comment]
Yes it seems like this is the problem, and the fix was merged in the develop branch. 
Any idea when this will be included in the release ?
