### ISSUE TITLE
Allow certain assertion statements without an equality check

### ISSUE THREAD

**Issue by iAmMichaelConnor** [Zokrates/ZoKrates#547]
Hi team!

I've been trying to split my code up into neat modules. Modules make code more re-usable and all that good stuff.

In some cases, I'm effectively 'outsourcing' some equality checks to other modules. Therefore it feels sensible to not repeat any equality check in the calling function. But then I get an error that `Assertion statements should be an equality check`.

**Example**: (I haven't checked whether this compiles, I'm just trying to give a minimal example):

Basic example WITHOUT outsourcing the equality check:
main-file.zok:
```
main ( field a, private field b, private field c ) -> ():
    a == b * c
    return
```
^^^ this works

The same example WITH outsourcing the equality check:
main-file.zok:
```
import "./common/check-multiplication.zok" as checkMultiplication
main ( field a, private field b, private field c ) -> ():
    checkMultiplication(a, b, c) // this line fails
    return
```

check-multiplication.zok:
```
main ( field a, private field b, private field c ) -> ():
    a == b * c
    return
```

^^^ this would fail, with:

`'not yet implemented: Assertion statements should be an equality check, found checkMultiplication(a, b, c)'`

I could modify this by returning a `1` from the `check-multiplication.zok` file, but this isn't ideal (because the `check-multiplication.zok` file contains a valid function).

What would be ideal, is permitting checkMultiplication(a, b, c) as a standalone line, because it contains the relevant equality checks.

**Comment by Schaeff** [comment]
Hi Michael, thanks for this.

I think it makes sense to extend assertion statements to any boolean, not just `a == b`
However, are you suggesting that assertion statements should also accept calls to functions with no return value? Ie in your example, isn't it cleaner to have `checkMultiplication(a, b, c)` return a boolean rather than returning nothing and failing as a side effect?

**Comment by Schaeff** [comment]
Closing as this issue is inactive, feel free to reopen @iAmMichaelConnor !
