### ISSUE TITLE
Add a modulus operator

### ISSUE THREAD

**Issue by JacobEberhardt** [Zokrates/ZoKrates#606]
The modulus operation is commonly used in cryptographic protocols and currently not supported in ZoKrates.

I propose to add a modulus operator `%` with the following syntax and semantics:
`a%n =  r`. Then, `a=n*w + r`.

A naive implementation could use the [euclidean division algorithm](https://en.wikipedia.org/wiki/Euclidean_division). 
Yet, this would require many constraints in the ZIR.
To support the modulo operation efficiently, we should introduce a new directive to derive the quotient `w` externally, i.e., outside of the ZIR constraints.
Receiving a `w`candidate, we simply perform the following check in a single ZIR constraint to ensure it's valid:
`a=n*w+r`

In a first step, the implementation for the field type seems sufficient. 
However, `w`needs to be bounded to prevent unexpected overflow effects, here.
This may indicate that an implementation for the unit types is more appropriate.

**Comment by Schaeff** [comment]
Nice! I think it would make sense to write a bit more about how this would be used to decide what it should look like:
- how big would these parameters typically be?
- are some of them required to be compile-time constants?

Also, shouldn't there be a check that `r < n` ?

**Comment by JacobEberhardt** [comment]
We added a modulus operator together with floored integer division for unsigned integer types in https://github.com/Zokrates/ZoKrates/pull/706.
