### ISSUE TITLE
How does the compare operator work?

### ISSUE THREAD

**Issue by james-ray** [Zokrates/ZoKrates#608]
I read some docs about the zksnarks and the constraints matrix, seems like it can well implement a proof about the equality of s.a * s.b == s.c.  I find some zok examples about the compare operator, and I write a simple program:
```
def main(private field a) -> (field):
        field x = if  a < 5555 then 3333 else 4444 fi
        x == 3333
	return 1
```
I compile the program and want to see how the compare operator is implemented, and find the lines below in the ztf file:
```
...
+ 34359738368 * _729 + 17179869184 * _730 + 8589934592 * _731 + 4294967296 * _732 + 2147483648 * _733 + 1073741824 * _734 + 536870912 * _735 + 268435456 * _736 + 134217728 * _737 + 67108864 * _738 + 33554432 * _739 + 16777216 * _740 + 8388608 * _741 + 4194304 * _742 + 2097152 * _743 + 1048576 * _744 + 524288 * _745 + 262144 * _746 + 131072 * _747 + 65536 * _748 + 32768 * _749 + 16384 * _750 + 8192 * _751 + 4096 * _752 + 2048 * _753 + 1024 * _754 + 512 * _755 + 256 * _756 + 128 * _757 + 64 * _758 + 32 * _759 + 16 * _760 + 8 * _761 + 4 * _762 + 2 * _763 + 1 * _764) == (-11110) * ~one + 2 * _0
	(1 * ~one) * (3333 * ~one) == 4444 * ~one + (-1111) * _764
	(1 * ~one) * (1 * ~one) == 1 * ~out_0
```
It seems like zokrates thinks that _764 is 1 stands for the expression is negative and _764 is 0 stands for the expression is positive.
How does this statement come from?
Below is my analysis:
1. _764 should be consistent with _511, both 0 or both 1, coz they are the only odd bits, and the expression is expected to be even here.
2. If _511=1, we are still able to get a positive even expression with _764=1.
So as far I concern, _764=1 can not be used as the judgement whether the expression is negative, though _764=0 can deduce to _511=0 then the expression is positive.

Is there something I understand wrong?
I am modifying the witness, to let a false witness to pass the check.
I input a=5556, it should fail the test, but I modify the witness to fit 5556 and let it still pass the check.

where does this number come from?
```
(-7414231717174750794300032619171286606889616317210963838766006185586667290625) * _511
```
Is this number any special? or is it just greater than
7237005577332262213973186563042994240829374041602535252466099000494570602496 ?

**Comment by Maping0412** [comment]
If the input a=5556, it should fail as the logic of the program.
But we modify the witness file, the method of modification is as follows:
   step 1: modify the bits from _512 to _764  to the bits of "7414231717174750794300032619171286606889616317210963838766006185586667290625", thus the sum from  _511 to _764 is 0;
   step 2: set _763 from ０ to 1, so sum from _511 to _764 is 2 which equals to "(-11110) * ~one + 2 * _0";
We use the modified witness to generate proof.json, it  successfully generated. 
We deploy the verifier contract to Remix, and we test the proof. The call succeeds.

**Comment by Schaeff** [comment]
Hi @james-ray thanks for reporting this, we identified the issue and will release a patch
