### ISSUE TITLE
off-chain proof verification using zokrates-cli

### ISSUE THREAD

**Issue by tHeMaskedMan981** [Zokrates/ZoKrates#630]
In some applications, the proofs generated using zokrates take longer to verify and therefore exceed block gas limit. for eg, when the number of public inputs is large, every input results in an extra on-chain elliptic curve scalar multiplication and addition. It would be great if we have another way of verifying the proofs off-chain, something like this - 
```bash
$ zokrates verify --proof proof.json --vk verification.key 
```

**Comment by Schaeff** [comment]
This is already on the `develop` branch and will be available in the next release!
