### ISSUE TITLE
Groth16 keys generated for the same circuit using setup are the same each time it is run

### ISSUE THREAD

**Issue by ChaitanyaKonda** [Zokrates/ZoKrates#632]
To call `create_random_proof` and `generate_random_parameters` for groth16 from bellman, zokrates uses a random number generator rng `let rng = &mut ChaChaRng::new_unseeded();`. This function `new_unseeded()` within rand crate seems to use ChaCha random number generator using the default fixed key of 8 zero words. As a result anytime setup is run on the same circuit, it produces the same set of proving and verification keys. Is there a reason for this? It might be useful to have an rng to accept entropy instead of a fixed key such that the keys generated are different each time for the same circuit. For non deterministic rng, Rand 0.7 crate provides rng created with entropy based on the target OS

**Comment by Schaeff** [comment]
Good call. We changed to ChaCha for wasm compatibility, happy to change to something else as long as that's covered too.

If there's no portable rng, we could have backend functions take an rng as parameter and have the caller instantiate it beforehand.

**Comment by ChaitanyaKonda** [comment]
Rand 0.7.3's `StdRng`( a CPRNG) also uses ChaCha block cipher with 20 rounds. The crate suggests that they may change this as new evidence of cipher security and performance becomes available. `StdRng` implements `SeedableRng` which provides `from_entropy` function which in itself depends on `getrandom` to provide entropy based on target OS. Taking a quick look at the `getrandom` crate, suggests that 

> For the wasm32-unknown-unknown target, one of the following features should be enabled:
> 
> wasm-bindgen
> stdweb

**Comment by dark64** [comment]
This is a tricky one. We can use `rand 0.7` specifically `OsRng` with `wasm-bindgen` feature enabled to preserve wasm compatibility and this would work for zexe. Unfortunately, bellman uses and expects `Rng` from `rand 0.4` which is not compatible with `rand 0.7`. We could use `OsRng` to generate the seed for `ChaChaRng` from `rand 0.4` and use that with bellman. Seems hacky though.
