### ISSUE TITLE
Do not depend on unstable compiler features

### ISSUE THREAD

**Issue by fulldecent** [Zokrates/ZoKrates#650]
Currently you cannot compile ZoKrates using the production Rust compiler:

```sh
cargo build --release
   Compiling zokrates_core v0.4.3 (/Users/williamentriken/Developer/ZoKrates/zokrates_core)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> zokrates_core/src/lib.rs:1:1
  |
1 | #![feature(box_patterns, box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `zokrates_core`.

To learn more, run the command again with --verbose.
```

I consider this a bug. We should avoid requiring people to use Nightly compilers in their build chain. Also, I don't know how to install Nightly compilers.

**Comment by Schaeff** [comment]
Duplicate of #25 yes it would be nice ofc but we use the box keyword a **lot**, so that it would hurt readability of the codebase a lot for the people we would try to help here, ie contributors. Last time I checked this was unfortunately not worth it, but thought are welcome here!

**Comment by fulldecent** [comment]
Sorry, closing duplicate. Will add discussion there.
