### ISSUE TITLE
Migrate from Circle CI to GitHub Actions

### ISSUE THREAD

**Issue by fulldecent** [Zokrates/ZoKrates#652]
It appears that Circle CI will mark commits as bad while not allowing you to see the actual CI test results. That's dumb.

We can consider to migrate to GitHub Actions. GitHub Actions is not dumb in this way.

**Comment by Schaeff** [comment]
Hey I don't think I see what you're talking about here, I do get a detailed report of what when wrong in CI. Can you explain a bit more?

**Comment by fulldecent** [comment]
I see an auth wall

![aaa](https://user-images.githubusercontent.com/382183/88865825-f0b7b800-d1d6-11ea-83bd-8e1494605e1c.gif)

**Comment by Schaeff** [comment]
Ok so you're saying you don't want to have to log into CircleCI?
I could see that argument and I don't have anything against GH Actions, however is it strong enough to put a high priority on migrating?
