### ISSUE TITLE
Program with no public params produces invalid Solidity

### ISSUE THREAD

**Issue by gregdhill** [Zokrates/ZoKrates#664]
Following the [proof of preimage](https://zokrates.github.io/gettingstarted.html) tutorial, in `hashexample.zok` we require four private inputs. This would seem to produce invalid Solidity as the code generator produces `uint[0] memory input` in the function signature of `verifyTx`. See also the following example:

```zok
def main():
    return
```

**Comment by Schaeff** [comment]
Thanks for flagging, fixed, will be in the next release
