### ISSUE TITLE
Redefinition optimizer uses up all memory and does not compile

### ISSUE THREAD

**Issue by migeyel** [Zokrates/ZoKrates#665]
Trying to compile this code with the `--release` flag will cause the compiler to use up all the memory without any output:
```
def main(private field a, private field b) -> field:
    for field i in 0..128 do
        a = a + b
        b = a + b
    endfor
    return a
```
My hypothesis is that the redefinition optimizer is trying to keep track of linear combinations that grow exponentially in size.
If that's the case then one solution for it would be to keep track of each variable as a linear combination of several "irreducible" variables instead. Doing this, every variable inside the loop would be redefined to only a linear combination of the inputs.
If the above doesn't help then you could also give up and add another constraint to keep memory use down and actually be able to compile the code.

**Comment by migeyel** [comment]
I've forked the code and ran it. It seems that's exactly what's happening, it keeps track of huge linear combinations of the same flat variables. The solution should be a very simple conversion from `a + b + a + b + ...` to `K1 * a + K2 * b` when adding a new lc to the substitution map.

**Comment by Schaeff** [comment]
Very good catch, been trying to fix this and for some reason I hadn't tried this. This will be in the next release!
