### ISSUE TITLE
Stdlib packing function bugs

### ISSUE THREAD

**Issue by MirandaWood** [Zokrates/ZoKrates#679]
Hi all,

I noticed a couple of small bugs in the stdlib packing functions.

In `stdlib/utils/pack/u32/pack256.zok`:
```
import "EMBED/u32_to_bits" as to_bits
import "../bool/pack256"
```
the `pack256` function isn't imported. This, however, works:
 ```
import "EMBED/u32_to_bits" as to_bits
import "../bool/pack256" as pack256
```
(Or, `from "../bool/pack256.zok" import main as pack256`, using the new import syntax).

In `stdlib/utils/pack/bool/pack256.zok`:
```
def main(bool[256] input) -> field:

	field out = 0

	field len = 256

	for field j in 0..len do
		field i = len - (j + 1)
		out = out + if bits[i] then (2 ** j) else 0 fi
	endfor

    return out
```
the variable `bits` should be called `input`:
```
out = out + if input[i] then (2 ** j) else 0 fi
```
These are easily fixed, so I'm happy to create a PR!

Thanks,
Miranda

**Comment by Schaeff** [comment]
Hi @MirandaWood, thanks for flagging this, yes we would welcome a PR on this!

**Comment by JacobEberhardt** [comment]
Closing, since merged with https://github.com/Zokrates/ZoKrates/pull/684.
Thanks again, Miranda!
