### ISSUE TITLE
Add support for CP6-782

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#685]
In #681 we introduce BW6-761, whose proofs can be verified in BLS12-377 snarks.
It is an improvement over CP6-782 whose proofs can also be verified in BLS12-377 snarks, introduced in the original Zexe paper.

It seems like adding support for the original curve wouldn't be too much work. However, if BW6-761 is strictly better, it might not be worth it.

@kobigurk tagging you as you might have an opinion here?

**Comment by kobigurk** [comment]
Hey!

I think there's little reason to use CP6-782. All the projects using depth
1 constructions that I know (Celo, Aleo, EY) have moved to BW6-761. There's
also a richer work on optimizations that had been done for it.

**Comment by Schaeff** [comment]
Thanks @kobigurk , closing then!
