### ISSUE TITLE
Option to turn off unconstrained variables check during compute witness

### ISSUE THREAD

**Issue by Westlad** [Zokrates/ZoKrates#686]
When debugging a complex proof, it's very useful to be able to comment out an assert line to check if it's the source of an 'expected 0 to equal 1' problem.  The unconstrained variables check prevents one being able to do this anymore.  Would it be possible to turn it off for debugging, maybe with a '--no-unconstrained-check' option on compute-witness?

**Comment by Schaeff** [comment]
Thanks for this @Westlad !

Is this a correct description of your problem:

```
def main(field a):
   assert(a == 42) // <- commenting out this line isn't allowed
   return
```

You're mentioning witness computation, but the unused variable check happens at compilation. Is this what you meant?

If so, what we could do is make unconstrained variables a warning which can be ignored during compilation. Under the hood, that would insert a dummy constraint `a == 1 * a` per unused argument to bypass the bellman unused input check.

**Comment by Westlad** [comment]
Thanks @Schaeff, that's exactly what I was thinking of.
