### ISSUE TITLE
Use a stable version of zexe

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#689]
All zexe related dependencies now target the master branch at https://github.com/scipr-lab/zexe

We should either target a specific commit or use the latest stable tag.

**Comment by Schaeff** [comment]
Do you have an update on this @dark64 ? I feel like arkworks (formerly zexe) uses semantic versioning but not crates.io, we need to know if there's a way to prevent ark breaking ZoKrates.
