### ISSUE TITLE
Add u<n> literals or a field -> u<n> converter

### ISSUE THREAD

**Issue by qbzzt** [Zokrates/ZoKrates#693]
It is sometimes useful to specify `u8`, `u16`, or `u32` literal values. It would be easier if we could either specify them directly, or at least have an easy way to convert between `field` and `u<whatever>`.

**Comment by Schaeff** [comment]
#677 introduces inference on decimal literals, so that 42 can be interpreted as 42f or 42u32 or... depending on context.

Good point on field to uint, I had it on a branch, will check.

**Comment by Schaeff** [comment]
This is implemented, closing
