### ISSUE TITLE
Poor compiler performance on mimc

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#710]
Mimc takes a lot of time to compile.
The reason is linked to how we currently handle writes to arrays. In order to remove side effects in SSA, we currently apply the following transformation:

```
a[i] = 42
->
a_1 = [if i == j then a_0[j] else 42 for j in 0..len(a)]
```

This is very expensive in cases where we do a lot of writes.

Solutions for this could be:
- Finding another transformation which works well with SSA and doesn't have this blow up
- Excluding arrays from SSA?

**Comment by JacobEberhardt** [comment]
This is basically a result of our linear-scan memory model.
While efficient for small array sizes, a permutation-network-based memory abstraction could be a better approach for larger arrays. Such a construction is presented in [Buffer](https://eprint.iacr.org/2014/674.pdf). 
For small sizes of addressable memory, an implementation-level optimization is proposed in Appendix B-A of [xJsnark](https://akosba.github.io/papers/xjsnark.pdf).
This does not only impact compilation performance but also constraint count.

**Comment by Schaeff** [comment]
This is actually unrelated to the memory model, and more due to the side-effect-free approach we were taking. Now without SSA, this is fixed.
