### ISSUE TITLE
Zokrates?

### ISSUE THREAD

**Issue by eyooooo** [Zokrates/ZoKrates#745]
If any of you 3 that are members of this org used to go by @zokrates in the SNX discord - would love to catch up with you and share my personal Solidity/Ethereum progress :) We used to chat last year but havent heard from you since Sept. 

Didnt know how else to get in touch so I googled your nick and found this repo. If I am in the wrong spot, feel free to nuke this. 

Thanks

eyooo

**Comment by JacobEberhardt** [comment]
We coordinated internally and unfortunately, it wasn't one of us...
Good luck with your search, closing.
