### ISSUE TITLE
ztf file is not generated when light flag is used

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#748]
I think `*.ztf` files should be always generated, but the `light` flag should be a way to disable logging bigger programs to the console (so the output is less verbose).

Current implementation skips the generation of the `*.ztf` file when `light` flag is used. Other solution would be to introduce a new flag `verbose` for the logging but keep the `light` flag as is.

**Comment by Schaeff** [comment]
@JacobEberhardt any thoughts on this?

**Comment by JacobEberhardt** [comment]
I agree with Darko's analysis. `Light` was intended to disable logging to the console.

However, with the growing complexity of the compiler, the `*.ztf`file becomes less and less valuable to devs.
With the planned introduction of automatic packing (to optimize on-chain gas usage), the `*.ztf`will be even more decoupled.
What about having neither console nor `'*.ztf` logging by default and enabling those through flags only?

**Comment by Schaeff** [comment]
I would support that. The only downside to me is that beginners can be curious what the output looks like, but a flag could be enough there.

Shall we remove console logging entirely and only rely on the ztf file when the flag is on?

**Comment by Schaeff** [comment]
Also: printing the program seems to be taking a significant amount of time in compute-witness, I guess this should go as well.

**Comment by JacobEberhardt** [comment]
Yes, I support that. Printing is basically a historical artifact at this point and should not be a default.
Let's put it behind a `verbose` flag and show how that flag is used in our introductory documentation.

**Comment by Schaeff** [comment]
This is done? @dark64

**Comment by dark64** [comment]
> This is done? @dark64

Yes, this has been merged.
