### ISSUE TITLE
Can't install older version of zokrates

### ISSUE THREAD

**Issue by KaddieIII** [Zokrates/ZoKrates#760]
Good morning everybody,
yesterday I tried to install an older Version of ZoKrates (I need 0.5.x) but actually I found out that this is not as easy as I thought. 
Since the oneliner always installs the latest release-version I tried to fix this manually. But I just got some HTML-Code back, since it's using curl and something went wrong. 
I also tried to use "cargo build" but this throws errors. "cargo +nightly build" works fine, but when I type "zokrates --version" it sais "zokrates: command not found".

How do I get the older version running?

Thanks in advance!

**Comment by Schaeff** [comment]
You can find older releases here: https://github.com/Zokrates/ZoKrates/releases

**Comment by KaddieIII** [comment]
Sorry, but this didn't solve my problem. I know, how to find these older versions, but the installation fails. 

When I download these older versions and install them, my system doesn't recognize them ("zokrates: command not found"). When I use the oneliner-installation it always fetches the newest version of zokrates, which I don't need (zokrates -version => 0.6.4 instead of 0.5.x). How do I solve this?

**Comment by dark64** [comment]
Download a release you want eg. [0.5.3](https://github.com/Zokrates/ZoKrates/releases/tag/0.5.3), unpack to `$HOME/.zokrates` then run this commands:

```bash
export PATH=$PATH:$HOME/.zokrates/bin
export ZOKRATES_HOME=$HOME/.zokrates/stdlib
```
