### ISSUE TITLE
compiler bug: returned boolean of a function cannot be assigned to boolean array element

### ISSUE THREAD

**Issue by scaffino** [Zokrates/ZoKrates#763]
Hi,

I think I have found an compiler bug: the returned boolean value of a function cannot be assigned to an element of a boolean array. The error printed out is this: 
```
Compilation failed: Only assignment to identifiers is supported".
```

For sake of clarity, here is the specific case I am referring to:
- I have defined this function that returns a boolean 
```
def booleanXOR(bool bool1, bool bool2) -> (bool):
    bool xor = (bool1 || bool2) && !(bool1 && bool2)
    return xor
```
- Then, when I compile these two lines
```
bool[2] test = [false, true]
test[1] = booleanXOR(true, false)
```
I have the error reported above. 

No error occurs in the following case:
```
bool mytest = true
mytest = booleanXOR(true, false)
bool[2] test2 = [false, true]
test2[1] = mytest
```

Also, it would be nice to also have a Boolean XOR operator.

**Comment by Schaeff** [comment]
This is fixed in 0.6.4
