### ISSUE TITLE
Add keccak256 to stdlib

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#776]
As keccak256 is widely used in solidity, it would be nice to have this hash function supported in ZoKrates as well.

**Comment by scaffino** [comment]
Hi @dark64, it would also be nice to have keccak512. I am currently working in a ZoKates implementation of this keccak512 function.

**Comment by Schaeff** [comment]
That's good to know @scaffino ! Am I right that it's based on 64bit words? We have a PR adding u64, which should make this implementation easier (except the padding aspects if any)

**Comment by scaffino** [comment]
@Schaeff yes, this is true for keccak-f[1600] (https://keccak.team/keccak_specs_summary.html). 

I am taking the solidity smartpool sha3_512 implementation as an example (https://github.com/SmartPool/contracts/blob/develop/contracts/Ethash.sol) and, at the moment, by using ZoKrates booleans, I have completely finished writing the keccak-f[25] permutation.

**Comment by Schaeff** [comment]
Nice. Do you see any obstacle to using `u64` arithmetics (other than the fact that `u64` isn't merged yet)?

**Comment by scaffino** [comment]
@Schaeff no, I do not see any at the moment. I really think that u64 fits perfectly for the keccak512 implementation (of course NOT, AND, OR operations should be provided - also having XOR would be great but, in the worst case, can be defined by using not, and, or). Nevertheless, I am going to investigate further and, in case I find any obstacle, I let you know.

**Comment by Schaeff** [comment]
Great thank you, yes the operators you mentioned will be available.
