### ISSUE TITLE
Fix git flow

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#780]
Currently `master` is our default branch. Our release flow is that any commit to master will trigger a release in CI. Therefore master is only ever written to by merging `develop` where individual PRs actually happen.

This is annoying because then as `master` is the default branch, PRs target it by default, where actually we wanna target `develop`.

@leonardoalt made a good point to we could rename `master` to `deploy` or `release` (by the same token getting rid of the `master` term entirely), and make `develop` the default branch.

This would require carefully adjusting CI to the renamed `master` branch.

**Comment by Schaeff** [comment]
cc @dark64 any thoughts?

**Comment by dark64** [comment]
I think `master` (nowadays called `main`) should be considered as a stable version and should stay as a default branch (this is pretty much a standard on most git flows), but I agree we should probably trigger deployments on `release` branches (or even just tags). This way PR's can still target `master` and commit directly on the stable codebase (in case of hotfixes, minor improvements, docs, etc) without triggering releases, as `develop` is our development branch where we might introduce unstable code, breaking changes etc.

**Comment by Schaeff** [comment]
Yes, the default branch having to be "stable" was the main thing keeping me from doing this in the first place. However the workflow I described is pretty much what Solidity uses (except for the fact that they do manual releases instead of our "release when commit on master", but that's not a big difference IMO)

See https://github.com/ethereum/solidity, their default branch is develop.

This actually makes sense to me, because anyone cloning and building from source is in my opinion fine with having a more experimental version.

**Comment by Schaeff** [comment]
Will submit pr with renamed branch, then can make dev default
