### ISSUE TITLE
Assertions should error out if the value is evaluated to false

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#812]
## Abstract
Assertion should error out on compilation if the value is evaluated to `false`.

## Motivation
There are cases where input values must be asserted e.g.:

```zokrates
def func<N>(field[N] inputs) -> bool:
    assert(N > 0 && N <= 6) // assert that the N is in [1, 6]
    .... // some code
    return true

def main():
    bool b = func([1, 2, 3, 4, 5, 6, 7]) // this should not be allowed
    return
```

## Specification

If an assertion `assert(e)` where `e` is an expression gets evaluated to `assert(false)`, the compiler should gracefully exit with an appropriate message.

## Backwards Compatibility
Should be compatible.

**Comment by Schaeff** [comment]
This can be implemented in typed propagation.
