### ISSUE TITLE
Migrate cross compilation to CircleCI

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#818]
## Description

Travis times out on our cross compilation jobs. It's time to move away from it.

**Comment by dark64** [comment]
Quick solution: it is possible to increase the timeout by using a `travis_wait` command https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

Long term we should migrate to CircleCI.

**Comment by Schaeff** [comment]
Good spot, let's try that. I started experimenting with Circle but not quite there yet.
