### ISSUE TITLE
RuntimeError: unreachable with zokrates-js:1.0.28+

### ISSUE THREAD

**Issue by coeniebeyers** [Zokrates/ZoKrates#827]
## Description

I'm seeing some interesting behaviour with the versions. I'm going to create two separate issues, one for zokrates-js and one for zokrates.

On zokrates 0.6.3 and zokrates-js@1.0.27 my circuit works fine and I can generate proofs in js & verify them in solidity. However, once I get to zokrates-js@1.0.28 (or higher) I get interesting errors. For example, on zokrates 0.6.3 with zokrates-js@1.0.28 I get:

```bash
  1) Contract: MetaCoin
       should be able to verify a transaction:
     RuntimeError: unreachable
      at null.<anonymous> (wasm://wasm/010686e6:0:3841142)
      at null.<anonymous> (wasm://wasm/010686e6:0:3864264)
      at null.<anonymous> (wasm://wasm/010686e6:0:3902567)
      at null.<anonymous> (wasm://wasm/010686e6:0:3900104)
      at null.<anonymous> (wasm://wasm/010686e6:0:3902621)
      at null.<anonymous> (wasm://wasm/010686e6:0:3898105)
      at null.<anonymous> (wasm://wasm/010686e6:0:1785954)
      at generate_proof (wasm://wasm/010686e6:0:2600658)
      at Object.module.exports.generate_proof (node_modules/zokrates-js/node/pkg/index.js:156:20)
      at Object.generateProof (node_modules/zokrates-js/wrapper.js:68:29)
      at Context.<anonymous> (test/metacoin.js:94:36)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

whereas on zokrates-js1.0.27 it doesn't error at all.

The test code is:
```js
 74   it("should be able to verify a transaction", async function() {
 75     const source = (fs.readFileSync('./zokrates/main.zok')).toString()
 76     const zokratesProvider = await initialize()
 77     // compilation
 78     const artifacts = zokratesProvider.compile(source);
 79     // Compute witness
 80     const b = 5
 81     const b_s = b.toString().padStart(128, '0')
 82     const hash = crypto.createHash('sha256').update(b_s, 'hex').digest('hex')
 83 
 84     const mask_128lsb = BigInt('0x'+''.padStart(32, '0')+''.padStart(32, 'f'))
 85 
 86     const bigIntHash = BigInt('0x'+hash)
 87     const H_msb = bigIntHash >> 128n
 88     const H_lsb = bigIntHash & mask_128lsb
 89 
 90     const { witness, output } = zokratesProvider.computeWitness(artifacts, [b_s, H_msb.toString(10), H_lsb.toString(10)]);
 91 
 92     const provingKey = [...fs.readFileSync('./zokrates/proving.key')]
 93     // generate proof
 94     const proof = zokratesProvider.generateProof(artifacts.program, witness, provingKey);
 95 
 96     const instance = await MetaCoin.deployed()
 97     const result = await instance.verifyProof(proof.proof.a, proof.proof.b, proof.proof.c, proof.inputs)
 98     console.log({result})
 99   })

```

any idea if there is something that I'm doing wrong that can lead to this behaviour?

## Environment

- Compiler version: zokrates: 0.6.3, zokrates-js: 1.0.28, 1.0.29
- Operating system: Ubuntu 20.04.2 LTS 
- NodeJS: v14.15.4

## Steps to Reproduce

By using the below snippet, install zokrates-js 1.0.28 or 1.0.29, and use the test above, the unwanted "RuntimeError: unreachable" is obtained.

```zokrates
  1 import "hashes/sha256/512bitPacked" as sha256Packed
  2     
  3 def main(private field v1, field hash1In0, field hash1In1) -> bool:
  4   field[2] hash0InCheck = sha256Packed([0, 0, 0, v1])
  5   return hash0InCheck[0] == hash1In0 && hash0InCheck[1] == hash1In1
```

**Comment by dark64** [comment]
Hello @coeniebeyers, thanks for the report!

It seems to fail on generating the proof. My guess is if you would run setup here and pass the new proving key instead of reading an old one (which I assume is generated with an older zokrates version?) this code should work? As we do a lot of changes to the core, some breaking changes were introduced recently with newer versions, so mixing artifacts between different versions can cause issues like this. Let me know if this is the case, otherwise, we'll investigate further.

Btw you don't have to do ```[...fs.readFileSync('./zokrates/proving.key')]```, `generateProof` expects proving key as a `Uint8Array` / `Buffer`, so just passing the result of `readFileSync` should be fine.

**Comment by coeniebeyers** [comment]
Hi, thanks for taking a look and the tip!

This is potentially what was happening, I'll be more aware to not use artefacts of different versions and let you know.

**Comment by Schaeff** [comment]
Hey @coeniebeyers I'll close this as it looks like you found the issue. Feel free to open another issue if anything comes up.
