### ISSUE TITLE
Use alpine instead of ubuntu

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/ZoKrates#84]
Hey @Kyroy someone mentioned this to me, wondered if you had any thoughts?

**Comment by Schaeff** [comment]
Or something like this? https://github.com/rust-lang-nursery/docker-rust-nightly

**Comment by Kyroy** [comment]
I agree, but I am not sure if libsnark is running on alpine or the rust image

**Comment by JacobEberhardt** [comment]
According to #113 Nightly Rust is not packaged for alpine. Shall we close this, since we require nightly features?
