### ISSUE TITLE
Assignment to for loop counter should be an error

### ISSUE THREAD

**Issue by axic** [Zokrates/ZoKrates#850]
I did the following code trying to mimic an actual loop, before I understood this really just gets "unrolled":
```
  for u32 step in 0..HARD_STEP_LIMIT do
    ...
    step = if (step == step_limit) then HARD_STEP_LIMIT else step fi
  endfor
```

I think this may be something people could try doing, so perhaps it would make sense making assignment to the loop counter a compile time error?

**Comment by Schaeff** [comment]
I see...

On the one hand I see how it would prevent this misconception.
On the other hand, the language currently does not have the concept of not being able to assign to a variable, and assigning to the counter is not an error per se, as the loop is a shorthand for:

```
step = 0
step = if .....
step = 1
step = if .....
...
```

And in python the following runs 10 iterations

```python
for i in range(0, 10):
  i = 1
  print("iteration")
```

This is `for x in set` and not `for x = 0; x < N; x++` which has this test after each iteration.

Maybe we can find other ways to suggest that this is unrolled?

**Comment by axic** [comment]
Good point about Python, but more importantly based on the documentation it just seems reusing "variables" is an inherent feature.

I do not have any good idea, perhaps changing `for` to `unroll`: `unroll u32 step in 0 .. LIMIT do`.  I don't think it looks particularly nice, but at least would prompt the user to read about it before using it.

**Comment by Schaeff** [comment]
Ok seems like the best we can do for now is to update the documentation.
