### ISSUE TITLE
Installation for ARM64 (Apple M1) fails

### ISSUE THREAD

**Issue by yklose** [Zokrates/ZoKrates#857]
Hello, 
I want to install Zokrates on my Apple M1 with ARM64. As specified in the [https://zokrates.github.io/gettingstarted.html](url) I first tried using: 

`curl -LSfs get.zokrat.es | sh`
Unfortunately this results in the following error:
```
ZoKrates: Tag: latest (0.7.1)
ZoKrates: ERROR unknown CPU type: arm64
```

Then I tried installing it from source with:
```
git clone https://github.com/ZoKrates/ZoKrates
cd ZoKrates
cargo +nightly build --release
cd target/release
```

After that I added Zokrates to path by:
`export PATH=$PATH:$HOME/.zokrates/bin`

when running zokrates from the command line I however still can not execute it. 
`zsh: command not found: zokrates`

When running test.sh all tests are passed. 

Any suggestions how to fix this issue?

**Comment by yklose** [comment]
Resolved the Issue: 
I manually exported the "get.zokrat.es" and looked into the file. There is a configuration for aarch64 but not for arm64 (even though they are the same). I changed the name vom aarch64 to arm64 and executed the sh script locally on my computer. Works fine!

I changed
```
...
aarch64)
    _cputype=aarch64
    ;;
...
```
to 
```
...
arm64)
    _cputype=aarch64
    ;;
...
```

Would be super cool if you could update the file, so that everyone with M1 Apple can use the simple command:

`curl -LSfs get.zokrat.es | sh`

**Comment by Schaeff** [comment]
Thanks for this @yklose and glad you figured this out! We'll make this change
