### ISSUE TITLE
Understanding PGHR13 proof.json

### ISSUE THREAD

**Issue by menens** [Zokrates/ZoKrates#868]
Hi I'm trying to better understand the single elements of the proof.json file generated using the pghr13 proving scheme in relation to the protocol explained in the Pinocchio paper. My question is why has "b" two curve points? Shouldn't it be the encrypted and shifted evalutation of the "B" (or "W") polynomial, just like "a" and "c" and hence just a point on the curve?

**Comment by dark64** [comment]
`b` is in G2 whose coordinates are in the extension field, which means each coordinate has two field elements of the original field but it's still only one point
