### ISSUE TITLE
The new version cannot compile

### ISSUE THREAD

**Issue by WangXiaopai595** [Zokrates/ZoKrates#875]
After I finished writing the code, there was an error in the compilation. The error was as follows:“Error: No such file or directory Cannot read file EMBED.zok”

![image](https://user-images.githubusercontent.com/28752345/118804978-f3a3a680-b8d7-11eb-8d43-67876ea0410c.png)

**Comment by dark64** [comment]
Can you specify which version of the compiler are you using? This way of importing embeds is only supported with the latest version `>= 0.7.2`. I cannot reproduce the same issue.

**Comment by WangXiaopai595** [comment]
I have solved this problem by changing the version to 0.7.2 or above, thank you!
