### ISSUE TITLE
Parser accepts invalid code

### ISSUE THREAD

**Issue by dark64** [Zokrates/ZoKrates#882]
## Description

The pest parser accepts code that contains array access in the declaration, which is invalid code.

## Environment

- Compiler version: 0.7.3
- Operating system: Ubuntu 20.04 LTS

## Steps to Reproduce

```zokrates
def main():
    field[2] a[2] = [1, 2]
    return
```

will result in

```
Compiling ./test.zok

assertion failed: `(left == right)`
  left: `1`,
  right: `0` (zokrates_core/src/absy/from_ast.rs:252:21)
```

**Comment by Schaeff** [comment]
fix in parser
