### ISSUE TITLE
Huge loop sizes crash/bog down the compiler

### ISSUE THREAD

**Issue by axic** [Zokrates/ZoKrates#884]
The following piece of code will make the compiler use up a lot of memory (>20Gb) and the process gets killed:

```
def main():
    for u32 i in 0..4 do
        for u32 j in 0..(i-1) do
        endfor
    endfor
    return
```

If I replace the `(i-1)` part with a literal, it works and the above example creates 0 constraints as expected.

**Comment by axic** [comment]
Ah, so `(i-1)` can result in `(-1)` i.e. unrolling it 2^32 times?

**Comment by Schaeff** [comment]
Yes that's what's happening. I think this is a user error, but it's unfortunate that it triggers this huge memory use. I'm trying to think of ways to handle this better. There would be the option to disallow underflow at compile time (which can be confusing semantically) or issue a warning if we detect such a big loop (but still unroll it to keep the same semantics)

**Comment by axic** [comment]
> issue a warning if we detect such a big loop (but still unroll it to keep the same semantics)

This sounds like a sensible option.
