### ISSUE TITLE
DSL language grammar and documentation

### ISSUE THREAD

**Issue by testrain** [Zokrates/ZoKrates#89]
Thanks for the great effort, ZoKrates is really awesome! I'm wondering that:
1.  is there any documentation of the grammar of the DSL ZoKrates uses? Or how could I contribute to come up with one if currently not available, where should I learn about the grammar details? 

2. Also I'm wondering that is it possible to bypass this specific DSL and directly compiles solidity code? Forgive me as I'm not too clear about the complexity and workload behind this, can you please elaborate?

Thanks!

**Comment by Schaeff** [comment]
1.
Hi @jonnyhsy, we used to have a formal grammar for the language but it was not stable we haven't kept it up to date as we added core features. We're interested in formalising the grammar again so suggestions are welcome on that front! You can find the (outdated) grammar [here](https://github.com/JacobEberhardt/ZoKrates/commit/b4b5ae708aab12136e1c82e6db063d5b42689bb2)

 2.
So the DSL compiles to R1CS which you can think of as a sort of Assembly for zero knowledge proof systems, then from there you can generate a verifier which can run on the EVM. You'd still need R1CS to actually execute the computation (`compute-witness` in ZoKrates terms), only proof generation runs on Ethereum.

**Comment by Schaeff** [comment]
Oh sorry I misunderstood your question :)

In theory it's always possible, however you'd have to remove a lot from solidity (anything that's dynamic really). ZoKrates builds a language from the ground up as the R1CS abstraction is quite different from say the EVM. Check out this paper for an attempt to compile C code to SNARKs https://eprint.iacr.org/2013/507.pdf , it's an involved process that has a huge impact on performance and requires more than what's available as precompiles right now.

Also, other than developer UX I can't see why Solidity would be a good choice for this.

**Comment by Schaeff** [comment]
This will be part of #306
