### ISSUE TITLE
bit shift issues

### ISSUE THREAD

**Issue by cdemirkiran** [Zokrates/ZoKrates#895]
## Description
The return type of bit shifts might be different than the input type or the output might be miscomputed entirely. 

## Environment

- Compiler version:  develop
- Operating system: Ubuntu 20.04.2 

## Steps to Reproduce
open file in zokrates_cli/examples/truncate.zok and paste the code below:

`def main():
    u32 bit_len = 5
    u32 a = 33
    u32 b = 32
    u32 res = (a >> bit_len) << bit_len
    assert(res == b)`
 
 then run 
 `cargo test -p zokrates_cli`

**Comment by Schaeff** [comment]
Your example is lacking a `return` statement which is what the compiler is complaining about.
With that statement added, the assertion is verified.
