### ISSUE TITLE
const-array-length parameters make a function impossible to call

### ISSUE THREAD

**Issue by jpdoyle** [Zokrates/ZoKrates#903]
## Description

Calling a function which uses a `const u32` identifier as the size of an array causes the inliner to panic.

## Environment

- Compiler version: `commit 4b2c5e7085cd1bdaa6a219c3ffe3cc148a096cc0`
- Operating system: Linux

## Steps to Reproduce

Try to compile:
```
const u32 N = 1
def foo(bool[N] arr) -> bool:
    return true

def main(bool[N] arr):
    assert(foo(arr))
    return
```
I see the following error:
```
called `Option::unwrap()` on a `None` value (.../ZoKrates/zokrates_core/src/static_analysis/reducer/inline.rs:70:10)
This is unexpected, please submit a full bug report at https://github.com/Zokrates/ZoKrates/issues
```

**Comment by Schaeff** [comment]
Thanks for reporting this @jpdoyle
