### ISSUE TITLE
crash on windows 10, 

### ISSUE THREAD

**Issue by zhfnjust** [Zokrates/ZoKrates#940]
## Description

crash when compiling.
build from source, using latest commit  6271c5b7467abcd7d45aab4c85fcef7d58e1e70d

ubuntu and mac don't have such problem
## Environment

- Compiler version: 0.7.5
- Operating system: windows 10 x64

## Steps to Reproduce

```


def main(field a, field b) -> field:
    assert(a + b == 3)
    return 

```

![image](https://user-images.githubusercontent.com/995909/125311933-67a57c80-e366-11eb-892b-7bec00acaadd.png)

**Comment by Schaeff** [comment]
Hey thanks for reporting this, you omitted the environment part of the issue, could you give more details? Especially if you were building from source or using our binaries

**Comment by zhfnjust** [comment]
> Hey thanks for reporting this, you omitted the environment part of the issue, could you give more details? Especially if you were building from source or using our binaries

updated

**Comment by dark64** [comment]
This definitely seems like a bug, but you're missing a `field` value in the `return` statement

**Comment by zhfnjust** [comment]
> This definitely seems like a bug, but you're missing a `field` value in the `return` statement

error still happend after adding a field value in the return statement

**Comment by dark64** [comment]
Can you provide more information about this? I can't replicate the same issue on my Win 10 machine.
