### ISSUE TITLE
Error in Proof Generation

### ISSUE THREAD

**Issue by edoroth** [Zokrates/ZoKrates#958]
I get the following error - unfamiliar with rust and not sure what the cause is. Has this been experienced before?

Generating proof...
WARNING: You are using the G16 scheme which is subject to malleability. See zokrates.github.io/toolbox/proving_schemes.html#g16-malleability for implications.
called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: UnexpectedEof, error: "expected more bases skipping from source" }) (/Users/distiller/project/zokrates_core/src/proof_system/bellman/mod.rs:175:68)

**Comment by Schaeff** [comment]
Hi @edoroth thanks for reporting this, it could be handled more gracefully by the compiler.
One cause could be that you perform the setup phase for one circuit, but then try to generate a proof for another (probably bigger) circuit. Did you try making sure the setup and proof generation phase are run on the same program?

**Comment by edoroth** [comment]
Oh you may be right. I believe this was the cause of my issues. Thank you!
