### ISSUE TITLE
```internal error: entered unreachable code: identifiers should have been removed in constant inlining```

### ISSUE THREAD

**Issue by sshravan** [Zokrates/ZoKrates#964]
## Description

The following code snippet runs into ```internal error: entered unreachable code: identifiers should have been removed in constant inlining (/Users/distiller/project/zokrates_core/src/typed_absy/types.rs:1024:25)``` error.

## Environment

- Compiler version: ZoKrates 0.7.5
- Operating system: macOS

## Steps to Reproduce

```zokrates
const u32 SIZE = 2
struct Matrix{
	field[SIZE] a
}

def Init_Matrix() -> (Matrix):
	Matrix matrix = Matrix{a: [0; SIZE]}
	return matrix

const Matrix MAT = Init_Matrix()

def main(Matrix A):
	assert(A.a == MAT.a)
	return

```
Error:

```
Compiling toy.zok

internal error: entered unreachable code: identifiers should have been removed in constant inlining (/Users/distiller/project/zokrates_core/src/typed_absy/types.rs:1024:25)
This is unexpected, please submit a full bug report at https://github.com/Zokrates/ZoKrates/issues
```

However, switching to ```struct Matrix{field[2] a}``` instead of ```struct Matrix{field[SIZE] a}``` seems to solve this issue.

- How do I go about doing something like: ```const Matrix MAT = Init_Matrix()```?
- Also can structs be generic? Something like: ```struct Matrix<N>{field[N] a}``` ?

**Comment by Schaeff** [comment]
This does look like a bug, thanks!

**Comment by Schaeff** [comment]
- Generic structs are implemented on develop but not released yet.
- Right now calling a function as the right side of a const definition is not supported
