### ISSUE TITLE
PosOverflow when creating an array and hashing it

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#966]
## Description
When creating a long array and hashing it, the compiler crashes.

## Environment

- Compiler version: ZoKrates 0.7.5
- Operating system: Manjaro

## Steps to Reproduce
Paste this code into a file and compile (`zokrates compile -i filename.zok`):
```zokrates
import "hashes/sha256/sha256" as sha256dynamic

def main():
    u32[1][16] toHash = [[0; 16]]
    u32[8] gPrimary = sha256dynamic(toHash)
    return
```
It will work just fine.

However, make the array a bit longer and try again:
```zokrates
import "hashes/sha256/sha256" as sha256dynamic

def main():
    u32[50][16] toHash = [[0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16], [0; 16]]
    u32[8] gPrimary = sha256dynamic(toHash)
    return
```

This will crash
```
$ zokrates compile -i filename.zok
Compiling filename.zok

called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow } (/home/circleci/project/zokrates_core/src/static_analysis/uint_optimizer.rs:393:22)
This is unexpected, please submit a full bug report at https://github.com/Zokrates/ZoKrates/issues
```

**Comment by dark64** [comment]
Thanks for the report, we will look into it as this is definitely a bug. Btw, you can shorten your array to `[[0; 16]; 50]`

**Comment by m1cm1c** [comment]
@dark64 Thanks for looking into it!

I started out with `[[0; 16]; 50]` but spent a lot of time thinking that this syntax didn't work with nested arrays so I wanted to be sure and used the expanded version in my bug report. But thank you for the hint and confirming that it does indeed work with nested arrays. :)

**Comment by Schaeff** [comment]
Note for fix: we should use biguint in the uint optimizer max calculations, not u128.
