### ISSUE TITLE
Add range semantics to docs

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#971]
## Description
When using a for loop with a loop variable that decreases, the compiler crashes. It does not matter whether only literals or also compile time constants are part of the loop interval.

## Environment

- Compiler version: ZoKrates 0.7.5
- Operating system: Manjaro

## Steps to Reproduce
Compile
```zokrates
def main():
	for u32 i in 0..1 do
		u32 r = i
	endfor
	return
```
This compiles as expected.

Now swap the 0 and the 1:
```zokrates
def main():
	for u32 i in 0..1 do
		u32 r = i
	endfor
	return
```
This results in:
```
$ zokrates compile -i bug.zok 
Compiling bug.zok

Compilation failed:

bug.zok:
        Found a loop of size 0, which is larger than the maximum allowed of 1048576. Check the loop bounds, especially for underflows
```

## Additional Request
It's really counter-intuitive that the right bound is not included when using the `..` syntax. E.g. bash does this:
```
$ echo {5..7}
5 6 7
$ echo {1..0}
1 0
```
If you think it's a good idea to stick to this behavior, you should probably add a warning to the documentation (https://zokrates.github.io/language/control_flow.html#for-loops). Not only people knowing `..` from other programming languages probably find this behavior very surprising but also people with a math background:
> When a and b are integers, the notation ⟦a, b⟧, or [a .. b] or {a .. b} or just a .. b, is sometimes used to indicate the interval of all integers between a and b included. The notation [a .. b] is used in some programming languages; in Pascal, for example, it is used to formally define a subrange type, most frequently used to specify lower and upper bounds of valid indices of an array.

(https://en.wikipedia.org/wiki/Interval_(mathematics)#Integer_intervals)

**Comment by Schaeff** [comment]
Hey @m1cm1c, essentially for ranges ZoKrates has the same behavior as at least both Python (which ZoKrates started with for its syntax and semantics) and Rust (by which it's increasingly inspired, and which is widely used in the applied cryptography community):
- The upper bound is excluded
- The size of a range is `floor_sub(upper_bound, lower_bound)`

See [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=47e6f2fd720edd0b419053ed271fc642) for the Rust behavior.

I understand the argument for symmetric inclusive ranges, but it's a matter of preference and we went for what applied cryptographers are already used to. You can reproduce the descending behavior with an intermediate variable inside the loop body.

Adding a note to the docs is a good idea though!

**Comment by m1cm1c** [comment]
> You can reproduce the descending behavior with an intermediate variable inside the loop body.

Yes, that's the workaround I'm currently using. I thought making ranges go in both directions was really useful but I can see that things get confusing if you omit the final value.

> Adding a note to the docs is a good idea though!

Nice to hear. :)
