### ISSUE TITLE
How to verify Zokrates' keccak256 in Solidity?

### ISSUE THREAD

**Issue by CarlJons0** [Zokrates/ZoKrates#983]
The data I generate on Zokrates' kecak256 is not the same as the data I generate on Solidity 'kecak256 ?

**Comment by CarlJons0** [comment]
The following code uses the same parameters to get different results.
`
function test(uint[] memory a) public pure returns (bytes32) { 
    bytes32 res= keccak256(abi.encodePacked(a)); return res; 
}

import "./utils/hash/keccak/256bit" as keccak256 
def main(u64[3] a) -> (u64[4]): 
    return keccak256(a)
`

**Comment by GalaxySciTech** [comment]
i meet the question too
