### ISSUE TITLE
Combatibility of functions using related generics lost when using structs

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#985]
## Description
The combatibility of functions using related generics and their respective call sits is lost when replacing arrays with structs.

## Environment

- Compiler version: 0.7.6
- Operating system: Manjaro

## Steps to Reproduce
Paste the following code into a file:
```zokrates
def myFct<N, N2>(u64[N] ignored) -> u64[N2]:
	assert(2*N == N2)

	return [0; N2]


const u32 N = 3
const u32 N2 = 2*N
def main(u64[N] arg) -> bool:
    u64[N2] someVariable = myFct(arg)

    return true
```

This compiles without issues:
```
$ zokrates compile -i bug.zok 
Compiling bug.zok

Compiled code written to 'out'
Number of constraints: 196
```

Now introduce an arbitrary generic struct and replace `u64[N]` with that struct's name (`u64[N] → SomeStruct<N>`):

```zokrates
struct SomeStruct<N> {
    u64[N] f
}

def myFct<N, N2>(SomeStruct<N> ignored) -> u64[N2]:
	assert(2*N == N2)

	return [0; N2]


const u32 N = 3
const u32 N2 = 2*N
def main(SomeStruct<N> arg) -> bool:
    u64[N2] someVariable = myFct(arg)

    return true
```

This fails to compile:
```
$ zokrates compile -i bug.zok 
Compiling bug.zok

Compilation failed:

bug.zok:
        Call site `bug.zok/myFct<_, _>(SomeStruct<3>) -> u64[6]` incompatible with declaration `bug.zok/myFct<N, N2>(SomeStruct<N>) -> u64[N2]`
```

Note, however, that the following code does compile. It still uses a generic struct but does not use related generics.

```zokrates
struct SomeStruct<N> {
    u64[N] f
}

def myFct<N>(SomeStruct<N> ignored) -> u64[N]:
	return [0; N]


const u32 N = 3
def main(SomeStruct<N> arg) -> bool:
    u64[N] someVariable = myFct(arg)

    return true
```

```
$ zokrates compile -i bug.zok 
Compiling bug.zok

Compiled code written to 'out'
Number of constraints: 196
```

**Comment by Schaeff** [comment]
Thanks for reporting this! I'm marking this as bug as the error message is incorrect. Otherwise it's an enhancement to bring struct to the same level of inference as arrays.

**Comment by m1cm1c** [comment]
As the generic behavior of structs apparently is supposed to be different from that of arrays, it would be great if that difference was documented. I'd suggest https://zokrates.github.io/language/generics.html as both the documentation of arrays and the documentation of structs link there.

**Comment by m1cm1c** [comment]
> Otherwise it's an enhancement to bring struct to the same level of inference as arrays.

I don't see how more inference in regards to structs in needed to compile the 2nd code example. The only difference between the 2nd and the 3rd code example is that there is an additional generics variable in the 2nd code example that does not concern the struct at all. In both of these cases, I'd expect the `N` of the `main()` function's `arg` to be used to determine the struct's generics parameter.
