### ISSUE TITLE
i want keccak256 to do this thing,can you help me

### ISSUE THREAD

**Issue by GalaxySciTech** [Zokrates/ZoKrates#996]
![image](https://user-images.githubusercontent.com/30950645/132945503-35fbfa28-49ab-46bb-896e-095ece5e1980.png)
I want to do keccak256 encoding, what should I do

**Comment by GalaxySciTech** [comment]
assert(keccak256(oriKey)==enKey)


who can help me to deal this
orikey and enkey both is string
for example orikey ="5". enKey="ceebf77a833b30520287ddd9478ff51abbdffa30aa90a8d655dba0e8a79ce0c1"
what can i do this
I have been using zok for a week, and I have not solved this problem yet, I am very sad
I will not use keccak256 for the string form

**Comment by Schaeff** [comment]
Hi @lailaibtc, Github issues, as specified in the issue template, are to report bugs or improvements proposals.
